package jp.nogami_rion.alchemical_power.init;

import jp.nogami_rion.alchemical_power.Alchemical_power;
import jp.nogami_rion.alchemical_power.registry.ModFluids;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.RegistryObject;

public class creativetab {
    //クリエイティブタグのレジストリ生成
    public static final DeferredRegister<CreativeModeTab> TABS = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, Alchemical_power.MODID);

    //レジストリにタブを追加
    public static final RegistryObject<CreativeModeTab> ALCHEMICAL_POWER_TAB;
    public static final RegistryObject<CreativeModeTab> ALCHEMICAL_POWER_FOODS_TAB;


    static {
        ALCHEMICAL_POWER_TAB = TABS.register("alchemical_power_tab", () -> CreativeModeTab.builder()
                .title(Component.translatable("creativetabs.alchemical_power_tab"))
                .icon(itemlist.PHILOSOPHERS_STONE.get()::getDefaultInstance)
                .displayItems((itemDisplayParameters, output) -> {
                    output.accept(itemlist.T0_PANAKEIA.get());
                    output.accept(itemlist.T1_PANAKEIA.get());
                    output.accept(itemlist.T2_PANAKEIA.get());
                    output.accept(itemlist.T3_PANAKEIA.get());
                    output.accept(itemlist.T4_PANAKEIA.get());
                    output.accept(itemlist.T5_PANAKEIA.get());
                    output.accept(itemlist.T6_PANAKEIA.get());
                    output.accept(itemlist.T7_PANAKEIA.get());
                    output.accept(itemlist.T1_PANAKEIA_CUBE.get());
                    output.accept(itemlist.T2_PANAKEIA_CUBE.get());
                    output.accept(itemlist.T3_PANAKEIA_CUBE.get());
                    output.accept(itemlist.T4_PANAKEIA_CUBE.get());
                    output.accept(itemlist.T5_PANAKEIA_CUBE.get());
                    output.accept(itemlist.T6_PANAKEIA_CUBE.get());
                    output.accept(itemlist.T7_PANAKEIA_CUBE.get());
                    output.accept(itemlist.PANAKEIA_BEARING_STONE.get());
                    output.accept(itemlist.X9_COBBLESTONE.get());
                    output.accept(itemlist.X225_COBBLESTONE.get());
                    output.accept(itemlist.X38025_COBBLESTONE.get());
                    output.accept(itemlist.IMITATED_BEDROCK.get());
                    output.accept(itemlist.PANAKEIA_REED_T0.get());
                    output.accept(itemlist.PANAKEIA_REED_T1.get());
                    output.accept(itemlist.PANAKEIA_REED_T2.get());
                    output.accept(itemlist.PANAKEIA_REED_T3.get());
                    output.accept(itemlist.PANAKEIA_REED_T4.get());
                    output.accept(itemlist.PANAKEIA_REED_T5.get());
                    output.accept(itemlist.PANAKEIA_REED_T6.get());
                    output.accept(itemlist.PANAKEIA_REED_T7.get());
                    output.accept(itemlist.ALCHETREE_LOG.get());
                    output.accept(itemlist.ALCHETREE_WOOD.get());
                    output.accept(itemlist.STRIPPED_ALCHETREE_LOG.get());
                    output.accept(itemlist.STRIPPED_ALCHETREE_WOOD.get());
                    output.accept(itemlist.ALCHETREE_STAIRS.get());
                    output.accept(itemlist.ALCHETREE_SLAB.get());
                    output.accept(itemlist.ALCHETREE_FENCE.get());
                    output.accept(itemlist.ALCHETREE_FENCE_GATE.get());
                    output.accept(itemlist.ALCHETREE_WALL.get());
                    output.accept(itemlist.ALCHETREE_DOOR.get());
                    output.accept(itemlist.ALCHETREE_TRAPDOOR.get());
                    output.accept(itemlist.ALCHETREE_BUTTON.get());
                    output.accept(itemlist.ALCHETREE_PRESSURE_PLATE.get());
                    output.accept(itemlist.ALCHETREE_SAPLINGS_T0.get());
                    output.accept(itemlist.ALCHETREE_SAPLINGS_T1.get());
                    output.accept(itemlist.ALCHETREE_SAPLINGS_T2.get());
                    output.accept(itemlist.ALCHETREE_SAPLINGS_T3.get());
                    output.accept(itemlist.ALCHETREE_SAPLINGS_T4.get());
                    output.accept(itemlist.ALCHETREE_SAPLINGS_T5.get());
                    output.accept(itemlist.ALCHETREE_SAPLINGS_T6.get());
                    output.accept(itemlist.ALCHETREE_SAPLINGS_T7.get());
                    output.accept(itemlist.ALCHETREE_PLANKS.get());
                    output.accept(itemlist.ALCHEMY_BEGINNERS_KIT.get());
                    output.accept(itemlist.ALCHEMY_INTERMEDIATE_KIT.get());
                    output.accept(itemlist.ALCHEMY_EXPERTS_KIT.get());
                    output.accept(itemlist.ULTIMATE_ALCHEMY_KIT.get());
                    output.accept(itemlist.PHILOSOPHERS_STONE.get());
                    output.accept(itemlist.T1_PANAKEIA_INGOT.get());
                    output.accept(itemlist.T2_PANAKEIA_INGOT.get());
                    output.accept(itemlist.T3_PANAKEIA_INGOT.get());
                    output.accept(itemlist.T4_PANAKEIA_GEM.get());
                    output.accept(itemlist.T5_PANAKEIA_GEM.get());
                    output.accept(itemlist.T6_PANAKEIA_INGOT.get());
                    output.accept(itemlist.UNITE_ALLOY.get());
                    output.accept(itemlist.UNITE_ALLOY_SMITHING_TEMPLATE.get());
                    output.accept(itemlist.SINGULARITY_INGOT_SMITHING_TEMPLATE.get());
                    output.accept(itemlist.ALCHEMY_TABLE.get());
                    output.accept(itemlist.HERMES_WORKBENCH.get());
                    output.accept(itemlist.TRANSCENDENTAL_TABLE.get());
                    output.accept(itemlist.ALCHEMY_TABLE_RE.get());
                    output.accept(itemlist.HERMES_WORKBENCH_RE.get());
                    output.accept(itemlist.TRANSCENDENTAL_TABLE_RE.get());
                    output.accept(itemlist.ALCHEMICAL_ENGRAVER.get());
                    output.accept(itemlist.RUNE_ACTIVATOR.get());
                    output.accept(itemlist.INFINITE_WATER_BARREL.get());
                    output.accept(itemlist.INFINITE_LAVA_BARREL.get());
                    output.accept(itemlist.T1_PANAKEIA_INGOT_BLOCK.get());
                    output.accept(itemlist.T2_PANAKEIA_INGOT_BLOCK.get());
                    output.accept(itemlist.T3_PANAKEIA_INGOT_BLOCK.get());
                    output.accept(itemlist.T4_PANAKEIA_GEM_BLOCK.get());
                    output.accept(itemlist.T5_PANAKEIA_GEM_BLOCK.get());
                    output.accept(itemlist.T6_PANAKEIA_INGOT_BLOCK.get());
                    output.accept(itemlist.UNITE_ALLOY_BLOCK.get());
                    output.accept(itemlist.HIGH_DENSITY_T1_PANAKEIA_INGOT.get());
                    output.accept(itemlist.HIGH_DENSITY_T2_PANAKEIA_INGOT.get());
                    output.accept(itemlist.HIGH_DENSITY_T3_PANAKEIA_INGOT.get());
                    output.accept(itemlist.HIGH_DENSITY_T4_PANAKEIA_GEM.get());
                    output.accept(itemlist.HIGH_DENSITY_T5_PANAKEIA_GEM.get());
                    output.accept(itemlist.HIGH_DENSITY_T6_PANAKEIA_INGOT.get());
                    output.accept(itemlist.HIGH_DENSITY_UNITE_ALLOY.get());
                    output.accept(itemlist.WISDOM_CRYSTAL.get());
                    output.accept(itemlist.COURAGE_CRYSTAL.get());
                    output.accept(itemlist.JUSTICE_CRYSTAL.get());
                    output.accept(itemlist.LOVE_CRYSTAL.get());
                    output.accept(itemlist.HOPE_CRYSTAL.get());
                    output.accept(itemlist.TEMPERANCE_CRYSTAL.get());
                    output.accept(itemlist.FAITH_CRYSTAL.get());
                    output.accept(itemlist.ORIGIN_OF_WISDOM.get());
                    output.accept(itemlist.ORIGIN_OF_COURAGE.get());
                    output.accept(itemlist.ORIGIN_OF_JUSTICE.get());
                    output.accept(itemlist.ORIGIN_OF_LOVE.get());
                    output.accept(itemlist.ORIGIN_OF_HOPE.get());
                    output.accept(itemlist.ORIGIN_OF_TEMPERANCE.get());
                    output.accept(itemlist.ORIGIN_OF_FAITH.get());
                    output.accept(itemlist.ARCANE_STAR.get());
                    output.accept(itemlist.ARCANE_DRAGON_EGG.get());
                    output.accept(itemlist.SINGULARITY.get());
                    output.accept(itemlist.BLANK_RUNE.get());
                    output.accept(itemlist.VOID_RUNE.get());
                    output.accept(itemlist.BASIC_ENGRAVING_INK.get());
                    output.accept(itemlist.ADVANCED_ENGRAVING_INK.get());
                    output.accept(itemlist.ELITE_ENGRAVING_INK.get());
                    output.accept(itemlist.ULTIMATE_ENGRAVING_INK.get());
                    output.accept(itemlist.BASIC_GRINDING_RUNE.get());
                    output.accept(itemlist.ADVANCED_GRINDING_RUNE.get());
                    output.accept(itemlist.ELITE_GRINDING_RUNE.get());
                    output.accept(itemlist.ULTIMATE_GRINDING_RUNE.get());
                    output.accept(itemlist.BASIC_GRANULATING_RUNE.get());
                    output.accept(itemlist.ADVANCED_GRANULATING_RUNE.get());
                    output.accept(itemlist.ELITE_GRANULATING_RUNE.get());
                    output.accept(itemlist.ULTIMATE_GRANULATING_RUNE.get());
                    output.accept(itemlist.BASIC_SOFTENING_RUNE.get());
                    output.accept(itemlist.ADVANCED_SOFTENING_RUNE.get());
                    output.accept(itemlist.ELITE_SOFTENING_RUNE.get());
                    output.accept(itemlist.ULTIMATE_SOFTENING_RUNE.get());
                    output.accept(itemlist.BASIC_PURIFICATION_RUNE.get());
                    output.accept(itemlist.ADVANCED_PURIFICATION_RUNE.get());
                    output.accept(itemlist.ELITE_PURIFICATION_RUNE.get());
                    output.accept(itemlist.ULTIMATE_PURIFICATION_RUNE.get());
                    output.accept(itemlist.RUNE_OF_FRUITS.get());
                    output.accept(itemlist.RUNE_OF_EQUIVALENT.get());
                    output.accept(itemlist.RUNE_OF_REPRODUCTION.get());
                    output.accept(itemlist.T1_COMBUSTION_RUNE.get());
                    output.accept(itemlist.T2_COMBUSTION_RUNE.get());
                    output.accept(itemlist.T3_COMBUSTION_RUNE.get());
                    output.accept(itemlist.T4_COMBUSTION_RUNE.get());
                    output.accept(itemlist.T5_COMBUSTION_RUNE.get());
                    output.accept(itemlist.T6_COMBUSTION_RUNE.get());
                    output.accept(itemlist.T1_COMBUSTION_RUNE_BLOCK.get());
                    output.accept(itemlist.T2_COMBUSTION_RUNE_BLOCK.get());
                    output.accept(itemlist.T3_COMBUSTION_RUNE_BLOCK.get());
                    output.accept(itemlist.T4_COMBUSTION_RUNE_BLOCK.get());
                    output.accept(itemlist.T5_COMBUSTION_RUNE_BLOCK.get());
                    output.accept(itemlist.T6_COMBUSTION_RUNE_BLOCK.get());
                    output.accept(itemlist.SEMI_ETERNAL_FUEL.get());
                    output.accept(itemlist.CRUSHED_RAW_COPPER.get());
                    output.accept(itemlist.CRUSHED_RAW_IRON.get());
                    output.accept(itemlist.CRUSHED_RAW_GOLD.get());
                    output.accept(itemlist.CRUSHED_DIAMOND_ORE.get());
                    output.accept(itemlist.CRUSHED_EMERALD_ORE.get());
                    output.accept(itemlist.CRUSHED_ANCIENT_DEBRIS.get());
                    output.accept(itemlist.GRANULATED_COPPER.get());
                    output.accept(itemlist.GRANULATED_IRON.get());
                    output.accept(itemlist.GRANULATED_GOLD.get());
                    output.accept(itemlist.GRANULATED_DIAMOND.get());
                    output.accept(itemlist.GRANULATED_EMERALD.get());
                    output.accept(itemlist.GRANULATED_ANCIENT_DEBRIS.get());
                    output.accept(itemlist.SOFTENED_COPPER.get());
                    output.accept(itemlist.SOFTENED_IRON.get());
                    output.accept(itemlist.SOFTENED_GOLD.get());
                    output.accept(itemlist.SOFTENED_DIAMOND.get());
                    output.accept(itemlist.SOFTENED_EMERALD.get());
                    output.accept(itemlist.SOFTENED_ANCIENT_DEBRIS.get());
                    output.accept(itemlist.PURIFIED_COPPER.get());
                    output.accept(itemlist.PURIFIED_IRON.get());
                    output.accept(itemlist.PURIFIED_GOLD.get());
                    output.accept(itemlist.PURIFIED_DIAMOND.get());
                    output.accept(itemlist.PURIFIED_EMERALD.get());
                    output.accept(itemlist.PURIFIED_ANCIENT_DEBRIS.get());
                    output.accept(itemlist.COLLECTED_CRUSHED_RAW_COPPER.get());
                    output.accept(itemlist.COLLECTED_CRUSHED_RAW_IRON.get());
                    output.accept(itemlist.COLLECTED_CRUSHED_RAW_GOLD.get());
                    output.accept(itemlist.COLLECTED_CRUSHED_DIAMOND_ORE.get());
                    output.accept(itemlist.COLLECTED_CRUSHED_EMERALD_ORE.get());
                    output.accept(itemlist.COLLECTED_CRUSHED_ANCIENT_DEBRIS.get());
                    output.accept(itemlist.COLLECTED_GRANULATED_COPPER.get());
                    output.accept(itemlist.COLLECTED_GRANULATED_IRON.get());
                    output.accept(itemlist.COLLECTED_GRANULATED_GOLD.get());
                    output.accept(itemlist.COLLECTED_GRANULATED_DIAMOND.get());
                    output.accept(itemlist.COLLECTED_GRANULATED_EMERALD.get());
                    output.accept(itemlist.COLLECTED_GRANULATED_ANCIENT_DEBRIS.get());
                    output.accept(itemlist.COLLECTED_SOFTENED_COPPER.get());
                    output.accept(itemlist.COLLECTED_SOFTENED_IRON.get());
                    output.accept(itemlist.COLLECTED_SOFTENED_GOLD.get());
                    output.accept(itemlist.COLLECTED_SOFTENED_DIAMOND.get());
                    output.accept(itemlist.COLLECTED_SOFTENED_EMERALD.get());
                    output.accept(itemlist.COLLECTED_SOFTENED_ANCIENT_DEBRIS.get());
                    output.accept(itemlist.COLLECTED_PURIFIED_COPPER.get());
                    output.accept(itemlist.COLLECTED_PURIFIED_IRON.get());
                    output.accept(itemlist.COLLECTED_PURIFIED_GOLD.get());
                    output.accept(itemlist.COLLECTED_PURIFIED_DIAMOND.get());
                    output.accept(itemlist.COLLECTED_PURIFIED_EMERALD.get());
                    output.accept(itemlist.COLLECTED_PURIFIED_ANCIENT_DEBRIS.get());
                    output.accept(itemlist.PACKAGED_CRUSHED_RAW_COPPER.get());
                    output.accept(itemlist.PACKAGED_CRUSHED_RAW_IRON.get());
                    output.accept(itemlist.PACKAGED_CRUSHED_RAW_GOLD.get());
                    output.accept(itemlist.PACKAGED_CRUSHED_DIAMOND_ORE.get());
                    output.accept(itemlist.PACKAGED_CRUSHED_EMERALD_ORE.get());
                    output.accept(itemlist.PACKAGED_CRUSHED_ANCIENT_DEBRIS.get());
                    output.accept(itemlist.PACKAGED_GRANULATED_COPPER.get());
                    output.accept(itemlist.PACKAGED_GRANULATED_IRON.get());
                    output.accept(itemlist.PACKAGED_GRANULATED_GOLD.get());
                    output.accept(itemlist.PACKAGED_GRANULATED_DIAMOND.get());
                    output.accept(itemlist.PACKAGED_GRANULATED_EMERALD.get());
                    output.accept(itemlist.PACKAGED_GRANULATED_ANCIENT_DEBRIS.get());
                    output.accept(itemlist.PACKAGED_SOFTENED_COPPER.get());
                    output.accept(itemlist.PACKAGED_SOFTENED_IRON.get());
                    output.accept(itemlist.PACKAGED_SOFTENED_GOLD.get());
                    output.accept(itemlist.PACKAGED_SOFTENED_DIAMOND.get());
                    output.accept(itemlist.PACKAGED_SOFTENED_EMERALD.get());
                    output.accept(itemlist.PACKAGED_SOFTENED_ANCIENT_DEBRIS.get());
                    output.accept(itemlist.PACKAGED_PURIFIED_COPPER.get());
                    output.accept(itemlist.PACKAGED_PURIFIED_IRON.get());
                    output.accept(itemlist.PACKAGED_PURIFIED_GOLD.get());
                    output.accept(itemlist.PACKAGED_PURIFIED_DIAMOND.get());
                    output.accept(itemlist.PACKAGED_PURIFIED_EMERALD.get());
                    output.accept(itemlist.PACKAGED_PURIFIED_ANCIENT_DEBRIS.get());

                    output.accept(itemlist.T1_PANAKEIA_PICKAXE.get());
                    output.accept(itemlist.T2_PANAKEIA_PICKAXE.get());
                    output.accept(itemlist.T3_PANAKEIA_PICKAXE.get());
                    output.accept(itemlist.T4_PANAKEIA_PICKAXE.get());
                    output.accept(itemlist.T5_PANAKEIA_PICKAXE.get());
                    output.accept(itemlist.T6_PANAKEIA_PICKAXE.get());
                    output.accept(itemlist.UNITE_ALLOY_PICKAXE.get());
                    output.accept(itemlist.T1_PANAKEIA_AXE.get());
                    output.accept(itemlist.T2_PANAKEIA_AXE.get());
                    output.accept(itemlist.T3_PANAKEIA_AXE.get());
                    output.accept(itemlist.T4_PANAKEIA_AXE.get());
                    output.accept(itemlist.T5_PANAKEIA_AXE.get());
                    output.accept(itemlist.T6_PANAKEIA_AXE.get());
                    output.accept(itemlist.UNITE_ALLOY_AXE.get());
                    output.accept(itemlist.T1_PANAKEIA_SHOVEL.get());
                    output.accept(itemlist.T2_PANAKEIA_SHOVEL.get());
                    output.accept(itemlist.T3_PANAKEIA_SHOVEL.get());
                    output.accept(itemlist.T4_PANAKEIA_SHOVEL.get());
                    output.accept(itemlist.T5_PANAKEIA_SHOVEL.get());
                    output.accept(itemlist.T6_PANAKEIA_SHOVEL.get());
                    output.accept(itemlist.UNITE_ALLOY_SHOVEL.get());
                    output.accept(itemlist.T1_PANAKEIA_SWORD.get());
                    output.accept(itemlist.T2_PANAKEIA_SWORD.get());
                    output.accept(itemlist.T3_PANAKEIA_SWORD.get());
                    output.accept(itemlist.T4_PANAKEIA_SWORD.get());
                    output.accept(itemlist.T5_PANAKEIA_SWORD.get());
                    output.accept(itemlist.T6_PANAKEIA_SWORD.get());
                    output.accept(itemlist.UNITE_ALLOY_SWORD.get());
                    output.accept(itemlist.T1_PANAKEIA_HOE.get());
                    output.accept(itemlist.T2_PANAKEIA_HOE.get());
                    output.accept(itemlist.T3_PANAKEIA_HOE.get());
                    output.accept(itemlist.T4_PANAKEIA_HOE.get());
                    output.accept(itemlist.T5_PANAKEIA_HOE.get());
                    output.accept(itemlist.T6_PANAKEIA_HOE.get());
                    output.accept(itemlist.UNITE_ALLOY_HOE.get());
                    output.accept(itemlist.T1_PANAKEIA_HELMET.get());
                    output.accept(itemlist.T1_PANAKEIA_CHESTPLATE.get());
                    output.accept(itemlist.T1_PANAKEIA_LEGGINGS.get());
                    output.accept(itemlist.T1_PANAKEIA_BOOTS.get());
                    output.accept(itemlist.T2_PANAKEIA_HELMET.get());
                    output.accept(itemlist.T2_PANAKEIA_CHESTPLATE.get());
                    output.accept(itemlist.T2_PANAKEIA_LEGGINGS.get());
                    output.accept(itemlist.T2_PANAKEIA_BOOTS.get());
                    output.accept(itemlist.T3_PANAKEIA_HELMET.get());
                    output.accept(itemlist.T3_PANAKEIA_CHESTPLATE.get());
                    output.accept(itemlist.T3_PANAKEIA_LEGGINGS.get());
                    output.accept(itemlist.T3_PANAKEIA_BOOTS.get());
                    output.accept(itemlist.T4_PANAKEIA_HELMET.get());
                    output.accept(itemlist.T4_PANAKEIA_CHESTPLATE.get());
                    output.accept(itemlist.T4_PANAKEIA_LEGGINGS.get());
                    output.accept(itemlist.T4_PANAKEIA_BOOTS.get());
                    output.accept(itemlist.T5_PANAKEIA_HELMET.get());
                    output.accept(itemlist.T5_PANAKEIA_CHESTPLATE.get());
                    output.accept(itemlist.T5_PANAKEIA_LEGGINGS.get());
                    output.accept(itemlist.T5_PANAKEIA_BOOTS.get());
                    output.accept(itemlist.T6_PANAKEIA_HELMET.get());
                    output.accept(itemlist.T6_PANAKEIA_CHESTPLATE.get());
                    output.accept(itemlist.T6_PANAKEIA_LEGGINGS.get());
                    output.accept(itemlist.T6_PANAKEIA_BOOTS.get());
                    output.accept(itemlist.UNITE_ALLOY_HELMET.get());
                    output.accept(itemlist.UNITE_ALLOY_CHESTPLATE.get());
                    output.accept(itemlist.UNITE_ALLOY_LEGGINGS.get());
                    output.accept(itemlist.UNITE_ALLOY_BOOTS.get());

                    output.accept(itemlist.T1_PANAKEIA_INGOT_X81_COMPRESSED_PLATE.get());
                    output.accept(itemlist.T2_PANAKEIA_INGOT_X81_COMPRESSED_PLATE.get());
                    output.accept(itemlist.T3_PANAKEIA_INGOT_X81_COMPRESSED_PLATE.get());
                    output.accept(itemlist.T4_PANAKEIA_GEM_X81_COMPRESSED_PLATE.get());
                    output.accept(itemlist.T5_PANAKEIA_GEM_X81_COMPRESSED_PLATE.get());
                    output.accept(itemlist.T6_PANAKEIA_INGOT_X81_COMPRESSED_PLATE.get());
                    output.accept(itemlist.UNITE_ALLOY_X81_COMPRESSED_PLATE.get());
                    output.accept(itemlist.T1_PANAKEIA_INGOT_X2025_COMPRESSED_PLATE.get());
                    output.accept(itemlist.T2_PANAKEIA_INGOT_X2025_COMPRESSED_PLATE.get());
                    output.accept(itemlist.T3_PANAKEIA_INGOT_X2025_COMPRESSED_PLATE.get());
                    output.accept(itemlist.T4_PANAKEIA_GEM_X2025_COMPRESSED_PLATE.get());
                    output.accept(itemlist.T5_PANAKEIA_GEM_X2025_COMPRESSED_PLATE.get());
                    output.accept(itemlist.T6_PANAKEIA_INGOT_X2025_COMPRESSED_PLATE.get());
                    output.accept(itemlist.UNITE_ALLOY_X2025_COMPRESSED_PLATE.get());
                    output.accept(itemlist.WISDOM_CRYSTAL_PLATE.get());
                    output.accept(itemlist.COURAGE_CRYSTAL_PLATE.get());
                    output.accept(itemlist.JUSTICE_CRYSTAL_PLATE.get());
                    output.accept(itemlist.LOVE_CRYSTAL_PLATE.get());
                    output.accept(itemlist.HOPE_CRYSTAL_PLATE.get());
                    output.accept(itemlist.TEMPERANCE_CRYSTAL_PLATE.get());
                    output.accept(itemlist.FAITH_CRYSTAL_PLATE.get());

                    output.accept(itemlist.FOUNDATION_OF_RING.get());
                    output.accept(itemlist.ALCHEMISTS_RING.get());
                    output.accept(itemlist.GLUTTONYS_RING.get());
                    output.accept(itemlist.GREED_RING.get());
                    output.accept(itemlist.LEGGINGS_OF_SAGA.get());
                    output.accept(itemlist.BLADE_OF_VALOR.get());
                    output.accept(itemlist.CRIMSON_PLATE_OF_JUSTICE.get());
                    output.accept(itemlist.ETERNAL_FUEL.get());
                    output.accept(itemlist.THE_DESTROYER_OF_THE_RIAL.get());
                    output.accept(itemlist.MARCH_OF_THE_RULER.get());
                    output.accept(itemlist.ANGEL_RING.get());
                    output.accept(itemlist.COBBLESTONE_GENERATOR_Mk1.get());
                    output.accept(itemlist.COBBLESTONE_GENERATOR_Mk2.get());
                    output.accept(itemlist.COBBLESTONE_GENERATOR_Mk3.get());
                    output.accept(itemlist.COBBLESTONE_GENERATOR_Mk4.get());
                    output.accept(itemlist.COBBLESTONE_GENERATOR_Mk5.get());
                    output.accept(itemlist.COBBLESTONE_GENERATOR_Mk6.get());
                    output.accept(itemlist.COBBLESTONE_GENERATOR_Mk7.get());
                    output.accept(itemlist.COBBLESTONE_GENERATOR_Mk8.get());
                    output.accept(itemlist.X9_COBBLESTONE_GENERATOR_Mk1.get());
                    output.accept(itemlist.X9_COBBLESTONE_GENERATOR_Mk2.get());
                    output.accept(itemlist.X9_COBBLESTONE_GENERATOR_Mk3.get());
                    output.accept(itemlist.X9_COBBLESTONE_GENERATOR_Mk4.get());
                    output.accept(itemlist.X9_COBBLESTONE_GENERATOR_Mk5.get());
                    output.accept(itemlist.X9_COBBLESTONE_GENERATOR_Mk6.get());
                    output.accept(itemlist.X9_COBBLESTONE_GENERATOR_Mk7.get());
                    output.accept(itemlist.X9_COBBLESTONE_GENERATOR_Mk8.get());
                    output.accept(itemlist.X225_COBBLESTONE_GENERATOR_Mk1.get());
                    output.accept(itemlist.X225_COBBLESTONE_GENERATOR_Mk2.get());
                    output.accept(itemlist.X225_COBBLESTONE_GENERATOR_Mk3.get());
                    output.accept(itemlist.X225_COBBLESTONE_GENERATOR_Mk4.get());
                    output.accept(itemlist.X225_COBBLESTONE_GENERATOR_Mk5.get());
                    output.accept(itemlist.X225_COBBLESTONE_GENERATOR_Mk6.get());
                    output.accept(itemlist.X225_COBBLESTONE_GENERATOR_Mk7.get());
                    output.accept(itemlist.X225_COBBLESTONE_GENERATOR_Mk8.get());
                    output.accept(itemlist.X38025_COBBLESTONE_GENERATOR_Mk1.get());
                    output.accept(itemlist.X38025_COBBLESTONE_GENERATOR_Mk2.get());
                    output.accept(itemlist.X38025_COBBLESTONE_GENERATOR_Mk3.get());
                    output.accept(itemlist.X38025_COBBLESTONE_GENERATOR_Mk4.get());
                    output.accept(itemlist.X38025_COBBLESTONE_GENERATOR_Mk5.get());
                    output.accept(itemlist.X38025_COBBLESTONE_GENERATOR_Mk6.get());
                    output.accept(itemlist.X38025_COBBLESTONE_GENERATOR_Mk7.get());
                    output.accept(itemlist.X38025_COBBLESTONE_GENERATOR_Mk8.get());
                    output.accept(itemlist.SINGULARITY_NUGGET.get());
                    output.accept(itemlist.SINGULARITY_INGOT.get());
                    output.accept(itemlist.CROWN_OF_THE_SERAPH.get());
                    output.accept(itemlist.JUDICIAL_CARAPACE.get());
                    output.accept(itemlist.GAIT_OF_INSIGHT.get());
                    output.accept(itemlist.BOOTS_OF_AETHERLIGHT.get());
                    output.accept(itemlist.SEVEN_SWORDS_OF_TERMINUS.get());

                    output.accept(itemlist.ALCHETREE_MYSTERIOUS_SCARECROW.get());
                    output.accept(ModFluids.T1_PANAKEIA.bucket.get());
                    output.accept(ModFluids.T2_PANAKEIA.bucket.get());
                    output.accept(ModFluids.T3_PANAKEIA.bucket.get());
                    output.accept(ModFluids.T4_PANAKEIA.bucket.get());
                    output.accept(ModFluids.T5_PANAKEIA.bucket.get());
                    output.accept(ModFluids.T6_PANAKEIA.bucket.get());
                    output.accept(ModFluids.UNITE_ALLOY.bucket.get());
                    output.accept(ModFluids.SINGULARITY.bucket.get());

                    output.accept(itemlist.RUNE_CATALYST.get());
                    output.accept(itemlist.UNNATURAL_CATALYST.get());
                    output.accept(itemlist.INFINITY_PANAKEIA.get());
                    output.accept(itemlist.IMITATED_BEDROCKIUM_INGOT.get());

                    output.accept(itemlist.ALCHEMY_MACHINE_FRAME.get());
                    output.accept(itemlist.PAIN_CONVERTER.get());
                    output.accept(itemlist.AUTO_ALCHEMICAL_ASSEMBLER.get());
                    output.accept(itemlist.PANAKEIA_GENERATOR.get());

                    output.accept(itemlist.SPEED_UPGRADE_T1.get());
                    output.accept(itemlist.SPEED_UPGRADE_T2.get());
                    output.accept(itemlist.SPEED_UPGRADE_T3.get());
                    output.accept(itemlist.SPEED_UPGRADE_T4.get());
                    output.accept(itemlist.SPEED_UPGRADE_T5.get());
                    output.accept(itemlist.ENERGY_EFFICIENCY_UPGRADE_T1.get());
                    output.accept(itemlist.ENERGY_EFFICIENCY_UPGRADE_T2.get());
                    output.accept(itemlist.ENERGY_EFFICIENCY_UPGRADE_T3.get());
                    output.accept(itemlist.ENERGY_EFFICIENCY_UPGRADE_T4.get());
                    output.accept(itemlist.ENERGY_EFFICIENCY_UPGRADE_T5.get());
                    output.accept(itemlist.ENERGY_CAPACITY_UPGRADE_T1.get());
                    output.accept(itemlist.ENERGY_CAPACITY_UPGRADE_T2.get());
                    output.accept(itemlist.ENERGY_CAPACITY_UPGRADE_T3.get());
                    output.accept(itemlist.ENERGY_CAPACITY_UPGRADE_T4.get());
                    output.accept(itemlist.ENERGY_CAPACITY_UPGRADE_T5.get());
                    output.accept(itemlist.CRAFTING_TOOL_UPGRADE_T2.get());
                    output.accept(itemlist.CRAFTING_TOOL_UPGRADE_T3.get());
                    output.accept(itemlist.CRAFTING_TOOL_UPGRADE_T4.get());
                    output.accept(itemlist.CRAFTING_TOOL_UPGRADE_T5.get());


                })
                .build());

        ALCHEMICAL_POWER_FOODS_TAB = TABS.register("alchemical_power_foods_tab", () -> CreativeModeTab.builder()
                .title(Component.translatable("creativetabs.alchemical_power_foods_tab"))
                .icon(itemlist.COOKWARE_SET.get()::getDefaultInstance)
                .displayItems((itemDisplayParameters, output) ->{
                    output.accept(itemlist.COOKWARE_SET.get());

                    //食材系（材料）
                    output.accept(itemlist.TOMATO.get());
                    output.accept(itemlist.CABBAGE.get());
                    output.accept(itemlist.ONION.get());
                    output.accept(itemlist.CHEESE.get());
                    output.accept(itemlist.RAW_PASTA.get());
                    output.accept(itemlist.DOUGH.get());
                    output.accept(itemlist.FLOUR.get());
                    output.accept(itemlist.RICE.get());
                    output.accept(itemlist.SLICED_APPLE.get());
                    output.accept(itemlist.CHOPPED_SEAWEED.get());
                    output.accept(itemlist.NORI.get());
                    output.accept(itemlist.SALMON_ROE.get());
                    output.accept(itemlist.COD_ROE.get());
                    output.accept(itemlist.CHOCOLATE.get());
                    output.accept(itemlist.LEMON.get());
                    output.accept(itemlist.SALT.get());
                    output.accept(itemlist.VINEGAR.get());
                    output.accept(itemlist.COOKING_OIL.get());
                    output.accept(itemlist.BUTTER.get());
                    output.accept(itemlist.AZUKI_BEANS.get());

                    //食材系（飲料・ジャム系）
                    output.accept(itemlist.APPLE_JAM.get());
                    output.accept(itemlist.SWEET_BERRY_JAM.get());
                    output.accept(itemlist.GLOW_BERRY_JAM.get());
                    output.accept(itemlist.TOMATO_JAM.get());
                    output.accept(itemlist.CHORUS_FRUIT_JAM.get());
                    output.accept(itemlist.LEMON_JAM.get());
                    output.accept(itemlist.MELON_JAM.get());
                    output.accept(itemlist.PUMPKIN_JAM.get());
                    output.accept(itemlist.MILK_BOTTLE.get());
                    output.accept(itemlist.APPLE_JUICE.get());
                    output.accept(itemlist.LEMON_JUICE.get());
                    output.accept(itemlist.TOMATO_JUICE.get());
                    output.accept(itemlist.CARROT_JUICE.get());
                    output.accept(itemlist.WHEAT_JUICE.get());
                    output.accept(itemlist.MELON_JUICE.get());
                    output.accept(itemlist.PUMPKIN_JUICE.get());
                    output.accept(itemlist.SWEET_BERRY_JUICE.get());
                    output.accept(itemlist.GLOW_BERRY_JUICE.get());
                    output.accept(itemlist.CHORUS_FRUIT_JUICE.get());
                    output.accept(itemlist.HONEY_LEMON_JUICE.get());
                    output.accept(itemlist.SWEET_AZUKI_PASTE.get());

                    //食材系（ソース系）
                    output.accept(itemlist.TOMATO_SAUCE.get());
                    output.accept(itemlist.CHEESE_SAUCE.get());
                    output.accept(itemlist.CREAM_SAUCE.get());
                    output.accept(itemlist.VINAIGRETTE_SAUCE.get());

                    //食材系アイテム（スープ系）
                    output.accept(itemlist.TOMATO_SOUP.get());
                    output.accept(itemlist.CABBAGE_AND_EGG_SOUP.get());
                    output.accept(itemlist.ONION_SOUP.get());
                    output.accept(itemlist.TOMATO_CREAM_SOUP.get());
                    output.accept(itemlist.CHICKEN_NOODLE_SOUP.get());
                    output.accept(itemlist.BEEF_STEW.get());
                    output.accept(itemlist.SEAFOOD_CHOWDER.get());
                    output.accept(itemlist.PUMPKIN_THICK_SOUP.get());
                    output.accept(itemlist.POTATO_THICK_SOUP.get());

                    //食材系アイテム（パスタ・ご飯系）
                    output.accept(itemlist.MEAT_SAUCE_PASTA.get());
                    output.accept(itemlist.CREAM_PASTA.get());
                    output.accept(itemlist.MUSHROOM_RISOTTO.get());
                    output.accept(itemlist.CHEESE_RISOTTO.get());
                    output.accept(itemlist.TOMATO_RISOTTO.get());
                    output.accept(itemlist.FRIED_RICE.get());
                    output.accept(itemlist.OMELETTE_RICE.get());
                    output.accept(itemlist.RICE_BALL.get());
                    output.accept(itemlist.SALMON_SUSHI.get());
                    output.accept(itemlist.KOMBUJIME_COD_SUSHI.get());
                    output.accept(itemlist.SUSHI_ROLLS.get());

                    //食材系アイテム（パン・焼き菓子系）
                    output.accept(itemlist.CHEESE_BREAD.get());
                    output.accept(itemlist.ONION_BREAD.get());
                    output.accept(itemlist.TOMATO_FOCACCIA.get());
                    output.accept(itemlist.PIZZA_DOUGH.get());
                    output.accept(itemlist.PIZZA_BEFORE_BAKING.get());
                    output.accept(itemlist.PIZZA.get());
                    output.accept(itemlist.CALZONE_BEFORE_BAKING.get());
                    output.accept(itemlist.CALZONE.get());
                    output.accept(itemlist.CHEESE_CRACKER.get());
                    output.accept(itemlist.CHEESE_CAKE.get());
                    output.accept(itemlist.CHOCOLATE_CAKE.get());
                    output.accept(itemlist.LEMON_CAKE.get());
                    output.accept(itemlist.APPLE_PIE.get());
                    output.accept(itemlist.CBBBICS.get());

                    //食材系アイテム（野菜系）
                    output.accept(itemlist.COLESLAW.get());
                    output.accept(itemlist.CHEESE_BAKED_POTATO.get());
                    output.accept(itemlist.ONION_RING.get());
                    output.accept(itemlist.GRILLED_TOMATO_AND_CHEESE.get());
                    output.accept(itemlist.CABBAGE_ROLL.get());
                    output.accept(itemlist.FRIED_POTATO.get());
                    output.accept(itemlist.GREEN_SALAD.get());
                    output.accept(itemlist.POTATO_SALAD.get());

                    //食材系アイテム（肉系）
                    output.accept(itemlist.FRIED_CHICKEN.get());
                    output.accept(itemlist.FRIED_FISH.get());
                    output.accept(itemlist.HAMBURG_STEAK.get());
                    output.accept(itemlist.HAMBURGER.get());
                    output.accept(itemlist.STEVES_LAVA_CHICKEN.get());

                    //食材系アイテム（デザート・スナック系）
                    output.accept(itemlist.ICE_CREAM.get());
                    output.accept(itemlist.CHOCOLATE_ICE_CREAM.get());
                    output.accept(itemlist.LEMON_ICE_CREAM.get());
                    output.accept(itemlist.APPLE_ICE_CREAM.get());
                    output.accept(itemlist.SWEET_BERRY_SMOOTHIE.get());
                    output.accept(itemlist.GLOW_BERRY_SMOOTHIE.get());
                    output.accept(itemlist.RICE_PUDDING.get());
                    output.accept(itemlist.JAM_BUN.get());

                    output.accept(itemlist.OMG_STEW.get());
                    output.accept(itemlist.JCMOWFBFWSBPOOFBCICIM.get());

                }).build());
    }



    public static void register(IEventBus eventBus){
        TABS.register(eventBus);
    }
}
