package jp.nogami_rion.alchemical_power.init;

import jp.nogami_rion.alchemical_power.Alchemical_power;
import net.minecraft.core.registries.Registries;
import net.minecraft.network.chat.Component;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.RegistryObject;

public class creativetab {
    //クリエイティブタグのレジストリ生成
    public static final DeferredRegister<CreativeModeTab> TABS = DeferredRegister.create(Registries.CREATIVE_MODE_TAB, Alchemical_power.MODID);

    //レジストリにタブを追加
    public static final RegistryObject<CreativeModeTab> ALCHEMICAL_POWER_TAB;

    static {
        ALCHEMICAL_POWER_TAB = TABS.register("alchemical_power_tab", () -> CreativeModeTab.builder()
                .title(Component.translatable("creativetabs.alchemical_power_tab"))
                .icon(itemlist.PHILOSOPHERS_STONE.get()::getDefaultInstance)
                .displayItems((itemDisplayParameters, output) -> {
                    output.accept(itemlist.T0_PANAKEIA.get());
                    output.accept(itemlist.T1_PANAKEIA.get());
                    output.accept(itemlist.T2_PANAKEIA.get());
                    output.accept(itemlist.T3_PANAKEIA.get());
                    output.accept(itemlist.T4_PANAKEIA.get());
                    output.accept(itemlist.T5_PANAKEIA.get());
                    output.accept(itemlist.T6_PANAKEIA.get());
                    output.accept(itemlist.T7_PANAKEIA.get());
                    output.accept(itemlist.T1_PANAKEIA_CUBE.get());
                    output.accept(itemlist.T2_PANAKEIA_CUBE.get());
                    output.accept(itemlist.T3_PANAKEIA_CUBE.get());
                    output.accept(itemlist.T4_PANAKEIA_CUBE.get());
                    output.accept(itemlist.T5_PANAKEIA_CUBE.get());
                    output.accept(itemlist.T6_PANAKEIA_CUBE.get());
                    output.accept(itemlist.T7_PANAKEIA_CUBE.get());
                    output.accept(itemlist.PANAKEIA_BEARING_STONE.get());
                    output.accept(itemlist.X9_COBBLESTONE.get());
                    output.accept(itemlist.X225_COBBLESTONE.get());
                    output.accept(itemlist.X38025_COBBLESTONE.get());
                    output.accept(itemlist.IMITATED_BEDROCK.get());
                    output.accept(itemlist.PANAKEIA_REED_T0.get());
                    output.accept(itemlist.PANAKEIA_REED_T1.get());
                    output.accept(itemlist.PANAKEIA_REED_T2.get());
                    output.accept(itemlist.PANAKEIA_REED_T3.get());
                    output.accept(itemlist.PANAKEIA_REED_T4.get());
                    output.accept(itemlist.PANAKEIA_REED_T5.get());
                    output.accept(itemlist.PANAKEIA_REED_T6.get());
                    output.accept(itemlist.PANAKEIA_REED_T7.get());
                    output.accept(itemlist.ALCHEMY_BEGINNERS_KIT.get());
                    output.accept(itemlist.ALCHEMY_INTERMEDIATE_KIT.get());
                    output.accept(itemlist.ALCHEMY_EXPERTS_KIT.get());
                    output.accept(itemlist.ULTIMATE_ALCHEMY_KIT.get());
                    output.accept(itemlist.PHILOSOPHERS_STONE.get());
                    output.accept(itemlist.T1_PANAKEIA_INGOT.get());
                    output.accept(itemlist.T2_PANAKEIA_INGOT.get());
                    output.accept(itemlist.T3_PANAKEIA_INGOT.get());
                    output.accept(itemlist.T4_PANAKEIA_GEM.get());
                    output.accept(itemlist.T5_PANAKEIA_GEM.get());
                    output.accept(itemlist.T6_PANAKEIA_INGOT.get());
                    output.accept(itemlist.UNITE_ALLOY.get());
                    output.accept(itemlist.ALCHEMY_TABLE.get());
                    output.accept(itemlist.HERMES_WORKBENCH.get());
                    output.accept(itemlist.TRANSCENDENTAL_TABLE.get());
                    output.accept(itemlist.ALCHEMICAL_ENGRAVER.get());
                    output.accept(itemlist.RUNE_ACTIVATOR.get());
                    output.accept(itemlist.T1_PANAKEIA_INGOT_BLOCK.get());
                    output.accept(itemlist.T2_PANAKEIA_INGOT_BLOCK.get());
                    output.accept(itemlist.T3_PANAKEIA_INGOT_BLOCK.get());
                    output.accept(itemlist.T4_PANAKEIA_GEM_BLOCK.get());
                    output.accept(itemlist.T5_PANAKEIA_GEM_BLOCK.get());
                    output.accept(itemlist.T6_PANAKEIA_INGOT_BLOCK.get());
                    output.accept(itemlist.UNITE_ALLOY_BLOCK.get());
                    output.accept(itemlist.HIGH_DENSITY_T1_PANAKEIA_INGOT.get());
                    output.accept(itemlist.HIGH_DENSITY_T2_PANAKEIA_INGOT.get());
                    output.accept(itemlist.HIGH_DENSITY_T3_PANAKEIA_INGOT.get());
                    output.accept(itemlist.HIGH_DENSITY_T4_PANAKEIA_GEM.get());
                    output.accept(itemlist.HIGH_DENSITY_T5_PANAKEIA_GEM.get());
                    output.accept(itemlist.HIGH_DENSITY_T6_PANAKEIA_INGOT.get());
                    output.accept(itemlist.HIGH_DENSITY_UNITE_ALLOY.get());
                    output.accept(itemlist.WISDOM_CRYSTAL.get());
                    output.accept(itemlist.COURAGE_CRYSTAL.get());
                    output.accept(itemlist.JUSTICE_CRYSTAL.get());
                    output.accept(itemlist.LOVE_CRYSTAL.get());
                    output.accept(itemlist.HOPE_CRYSTAL.get());
                    output.accept(itemlist.TEMPERANCE_CRYSTAL.get());
                    output.accept(itemlist.FAITH_CRYSTAL.get());
                    output.accept(itemlist.ORIGIN_OF_WISDOM.get());
                    output.accept(itemlist.ORIGIN_OF_COURAGE.get());
                    output.accept(itemlist.ORIGIN_OF_JUSTICE.get());
                    output.accept(itemlist.ORIGIN_OF_LOVE.get());
                    output.accept(itemlist.ORIGIN_OF_HOPE.get());
                    output.accept(itemlist.ORIGIN_OF_TEMPERANCE.get());
                    output.accept(itemlist.ORIGIN_OF_FAITH.get());
                    output.accept(itemlist.ARCANE_STAR.get());
                    output.accept(itemlist.ARCANE_DRAGON_EGG.get());
                    output.accept(itemlist.SINGULARITY.get());
                    output.accept(itemlist.BLANK_RUNE.get());
                    output.accept(itemlist.VOID_RUNE.get());
                    output.accept(itemlist.BASIC_ENGRAVING_INK.get());
                    output.accept(itemlist.ADVANCED_ENGRAVING_INK.get());
                    output.accept(itemlist.ELITE_ENGRAVING_INK.get());
                    output.accept(itemlist.ULTIMATE_ENGRAVING_INK.get());
                    output.accept(itemlist.BASIC_GRINDING_RUNE.get());
                    output.accept(itemlist.ADVANCED_GRINDING_RUNE.get());
                    output.accept(itemlist.ELITE_GRINDING_RUNE.get());
                    output.accept(itemlist.ULTIMATE_GRINDING_RUNE.get());
                    output.accept(itemlist.BASIC_GRANULATING_RUNE.get());
                    output.accept(itemlist.ADVANCED_GRANULATING_RUNE.get());
                    output.accept(itemlist.ELITE_GRANULATING_RUNE.get());
                    output.accept(itemlist.ULTIMATE_GRANULATING_RUNE.get());
                    output.accept(itemlist.BASIC_SOFTENING_RUNE.get());
                    output.accept(itemlist.ADVANCED_SOFTENING_RUNE.get());
                    output.accept(itemlist.ELITE_SOFTENING_RUNE.get());
                    output.accept(itemlist.ULTIMATE_SOFTENING_RUNE.get());
                    output.accept(itemlist.BASIC_PURIFICATION_RUNE.get());
                    output.accept(itemlist.ADVANCED_PURIFICATION_RUNE.get());
                    output.accept(itemlist.ELITE_PURIFICATION_RUNE.get());
                    output.accept(itemlist.ULTIMATE_PURIFICATION_RUNE.get());
                    output.accept(itemlist.T1_COMBUSTION_RUNE.get());
                    output.accept(itemlist.T2_COMBUSTION_RUNE.get());
                    output.accept(itemlist.T3_COMBUSTION_RUNE.get());
                    output.accept(itemlist.T4_COMBUSTION_RUNE.get());
                    output.accept(itemlist.T5_COMBUSTION_RUNE.get());
                    output.accept(itemlist.T6_COMBUSTION_RUNE.get());
                    output.accept(itemlist.T1_COMBUSTION_RUNE_BLOCK.get());
                    output.accept(itemlist.T2_COMBUSTION_RUNE_BLOCK.get());
                    output.accept(itemlist.T3_COMBUSTION_RUNE_BLOCK.get());
                    output.accept(itemlist.T4_COMBUSTION_RUNE_BLOCK.get());
                    output.accept(itemlist.T5_COMBUSTION_RUNE_BLOCK.get());
                    output.accept(itemlist.T6_COMBUSTION_RUNE_BLOCK.get());
                    output.accept(itemlist.SEMI_ETERNAL_FUEL.get());
                    output.accept(itemlist.ETERNAL_FUEL.get());
                    output.accept(itemlist.CRUSHED_RAW_COPPER.get());
                    output.accept(itemlist.CRUSHED_RAW_IRON.get());
                    output.accept(itemlist.CRUSHED_RAW_GOLD.get());
                    output.accept(itemlist.CRUSHED_DIAMOND_ORE.get());
                    output.accept(itemlist.CRUSHED_EMERALD_ORE.get());
                    output.accept(itemlist.CRUSHED_ANCIENT_DEBRIS.get());
                    output.accept(itemlist.GRANULATED_COPPER.get());
                    output.accept(itemlist.GRANULATED_IRON.get());
                    output.accept(itemlist.GRANULATED_GOLD.get());
                    output.accept(itemlist.GRANULATED_DIAMOND.get());
                    output.accept(itemlist.GRANULATED_EMERALD.get());
                    output.accept(itemlist.GRANULATED_ANCIENT_DEBRIS.get());
                    output.accept(itemlist.SOFTENED_COPPER.get());
                    output.accept(itemlist.SOFTENED_IRON.get());
                    output.accept(itemlist.SOFTENED_GOLD.get());
                    output.accept(itemlist.SOFTENED_DIAMOND.get());
                    output.accept(itemlist.SOFTENED_EMERALD.get());
                    output.accept(itemlist.SOFTENED_ANCIENT_DEBRIS.get());
                    output.accept(itemlist.PURIFIED_COPPER.get());
                    output.accept(itemlist.PURIFIED_IRON.get());
                    output.accept(itemlist.PURIFIED_GOLD.get());
                    output.accept(itemlist.PURIFIED_DIAMOND.get());
                    output.accept(itemlist.PURIFIED_EMERALD.get());
                    output.accept(itemlist.PURIFIED_ANCIENT_DEBRIS.get());
                    output.accept(itemlist.T1_PANAKEIA_PICKAXE.get());
                    output.accept(itemlist.T2_PANAKEIA_PICKAXE.get());
                    output.accept(itemlist.T3_PANAKEIA_PICKAXE.get());
                    output.accept(itemlist.T4_PANAKEIA_PICKAXE.get());
                    output.accept(itemlist.T5_PANAKEIA_PICKAXE.get());
                    output.accept(itemlist.T6_PANAKEIA_PICKAXE.get());
                    output.accept(itemlist.UNITE_ALLOY_PICKAXE.get());
                    output.accept(itemlist.T1_PANAKEIA_AXE.get());
                    output.accept(itemlist.T2_PANAKEIA_AXE.get());
                    output.accept(itemlist.T3_PANAKEIA_AXE.get());
                    output.accept(itemlist.T4_PANAKEIA_AXE.get());
                    output.accept(itemlist.T5_PANAKEIA_AXE.get());
                    output.accept(itemlist.T6_PANAKEIA_AXE.get());
                    output.accept(itemlist.UNITE_ALLOY_AXE.get());
                    output.accept(itemlist.T1_PANAKEIA_SHOVEL.get());
                    output.accept(itemlist.T2_PANAKEIA_SHOVEL.get());
                    output.accept(itemlist.T3_PANAKEIA_SHOVEL.get());
                    output.accept(itemlist.T4_PANAKEIA_SHOVEL.get());
                    output.accept(itemlist.T5_PANAKEIA_SHOVEL.get());
                    output.accept(itemlist.T6_PANAKEIA_SHOVEL.get());
                    output.accept(itemlist.UNITE_ALLOY_SHOVEL.get());
                    output.accept(itemlist.T1_PANAKEIA_SWORD.get());
                    output.accept(itemlist.T2_PANAKEIA_SWORD.get());
                    output.accept(itemlist.T3_PANAKEIA_SWORD.get());
                    output.accept(itemlist.T4_PANAKEIA_SWORD.get());
                    output.accept(itemlist.T5_PANAKEIA_SWORD.get());
                    output.accept(itemlist.T6_PANAKEIA_SWORD.get());
                    output.accept(itemlist.UNITE_ALLOY_SWORD.get());
                    output.accept(itemlist.T1_PANAKEIA_HOE.get());
                    output.accept(itemlist.T2_PANAKEIA_HOE.get());
                    output.accept(itemlist.T3_PANAKEIA_HOE.get());
                    output.accept(itemlist.T4_PANAKEIA_HOE.get());
                    output.accept(itemlist.T5_PANAKEIA_HOE.get());
                    output.accept(itemlist.T6_PANAKEIA_HOE.get());
                    output.accept(itemlist.UNITE_ALLOY_HOE.get());
                    output.accept(itemlist.T1_PANAKEIA_HELMET.get());
                    output.accept(itemlist.T1_PANAKEIA_CHESTPLATE.get());
                    output.accept(itemlist.T1_PANAKEIA_LEGGINGS.get());
                    output.accept(itemlist.T1_PANAKEIA_BOOTS.get());
                    output.accept(itemlist.T2_PANAKEIA_HELMET.get());
                    output.accept(itemlist.T2_PANAKEIA_CHESTPLATE.get());
                    output.accept(itemlist.T2_PANAKEIA_LEGGINGS.get());
                    output.accept(itemlist.T2_PANAKEIA_BOOTS.get());
                    output.accept(itemlist.T3_PANAKEIA_HELMET.get());
                    output.accept(itemlist.T3_PANAKEIA_CHESTPLATE.get());
                    output.accept(itemlist.T3_PANAKEIA_LEGGINGS.get());
                    output.accept(itemlist.T3_PANAKEIA_BOOTS.get());
                    output.accept(itemlist.T4_PANAKEIA_HELMET.get());
                    output.accept(itemlist.T4_PANAKEIA_CHESTPLATE.get());
                    output.accept(itemlist.T4_PANAKEIA_LEGGINGS.get());
                    output.accept(itemlist.T4_PANAKEIA_BOOTS.get());
                    output.accept(itemlist.T5_PANAKEIA_HELMET.get());
                    output.accept(itemlist.T5_PANAKEIA_CHESTPLATE.get());
                    output.accept(itemlist.T5_PANAKEIA_LEGGINGS.get());
                    output.accept(itemlist.T5_PANAKEIA_BOOTS.get());
                    output.accept(itemlist.T6_PANAKEIA_HELMET.get());
                    output.accept(itemlist.T6_PANAKEIA_CHESTPLATE.get());
                    output.accept(itemlist.T6_PANAKEIA_LEGGINGS.get());
                    output.accept(itemlist.T6_PANAKEIA_BOOTS.get());
                    output.accept(itemlist.UNITE_ALLOY_HELMET.get());
                    output.accept(itemlist.UNITE_ALLOY_CHESTPLATE.get());
                    output.accept(itemlist.UNITE_ALLOY_LEGGINGS.get());
                    output.accept(itemlist.UNITE_ALLOY_BOOTS.get());
                    output.accept(itemlist.THE_DESTROYER_OF_THE_RIAL.get());
                    output.accept(itemlist.ANGEL_RING.get());




                })
                .build());
    }

    public static void register(IEventBus eventBus){
        TABS.register(eventBus);
    }
}
