package jp.nogami_rion.alchemical_power.init;


import jp.nogami_rion.alchemical_power.Alchemical_power;
import jp.nogami_rion.alchemical_power.item.*;
import jp.nogami_rion.alchemical_power.item.baseclass.CommonAlchemyMaterial;
import jp.nogami_rion.alchemical_power.item.baseclass.EpicAlchemyMaterial;
import jp.nogami_rion.alchemical_power.item.baseclass.RareAlchemyMaterial;
import jp.nogami_rion.alchemical_power.item.baseclass.UncommonAlchemyMaterial;
import jp.nogami_rion.alchemical_power.item.custom.FuelItem;
import net.minecraft.world.item.*;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class itemlist {
    //アイテムリストを生成
    private static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, Alchemical_power.MODID);
    public static final RegistryObject<Item> T0_PANAKEIA = ITEMS.register("t0_panakeia", T0_Panakeia::new);
    public static final RegistryObject<Item> T1_PANAKEIA = ITEMS.register("t1_panakeia", T1_Panakeia::new);
    public static final RegistryObject<Item> T2_PANAKEIA = ITEMS.register("t2_panakeia", T2_Panakeia::new);
    public static final RegistryObject<Item> T3_PANAKEIA = ITEMS.register("t3_panakeia", T3_Panakeia::new);
    public static final RegistryObject<Item> T4_PANAKEIA = ITEMS.register("t4_panakeia", T4_Panakeia::new);
    public static final RegistryObject<Item> T5_PANAKEIA = ITEMS.register("t5_panakeia", T5_Panakeia::new);
    public static final RegistryObject<Item> T6_PANAKEIA = ITEMS.register("t6_panakeia", T6_Panakeia::new);
    public static final RegistryObject<Item> T7_PANAKEIA = ITEMS.register("t7_panakeia", T7_Panakeia::new);
    public static final RegistryObject<Item> PANAKEIA_BEARING_STONE = ITEMS.register("panakeia_bearing_stone",() -> new BlockItem(blocklist.PANAKEIA_BEARING_STONE.get(), new Item.Properties()));
    public static final RegistryObject<Item> ALCHEMY_BEGINNERS_KIT = ITEMS.register("alchemy_beginners_kit",Alchemy_Bginners_Kit::new);
    public static final RegistryObject<Item> T1_PANAKEIA_INGOT = ITEMS.register("t1_panakeia_ingot",CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> T2_PANAKEIA_INGOT = ITEMS.register("t2_panakeia_ingot",CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> T3_PANAKEIA_INGOT = ITEMS.register("t3_panakeia_ingot", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> T4_PANAKEIA_GEM = ITEMS.register("t4_panakeia_gem", UncommonAlchemyMaterial::new);
    public static final RegistryObject<Item> T5_PANAKEIA_GEM = ITEMS.register("t5_panakeia_gem", UncommonAlchemyMaterial::new);
    public static final RegistryObject<Item> T6_PANAKEIA_INGOT = ITEMS.register("t6_panakeia_ingot", RareAlchemyMaterial::new);
    public static final RegistryObject<Item> UNITE_ALLOY = ITEMS.register("unite_alloy", Unite_Alloy::new);
    public static final RegistryObject<Item> T1_PANAKEIA_INGOT_BLOCK = ITEMS.register("t1_panakeia_ingot_block",() -> new BlockItem(blocklist.T1_PANAKEIA_INGOT_BLOCK.get(), new Item.Properties()));
    public static final RegistryObject<Item> T2_PANAKEIA_INGOT_BLOCK = ITEMS.register("t2_panakeia_ingot_block",() -> new BlockItem(blocklist.T2_PANAKEIA_INGOT_BLOCK.get(), new Item.Properties()));
    public static final RegistryObject<Item> T3_PANAKEIA_INGOT_BLOCK = ITEMS.register("t3_panakeia_ingot_block",() -> new BlockItem(blocklist.T3_PANAKEIA_INGOT_BLOCK.get(), new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> T4_PANAKEIA_GEM_BLOCK = ITEMS.register("t4_panakeia_gem_block",() -> new BlockItem(blocklist.T4_PANAKEIA_GEM_BLOCK.get(), new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> T5_PANAKEIA_GEM_BLOCK = ITEMS.register("t5_panakeia_gem_block",() -> new BlockItem(blocklist.T5_PANAKEIA_GEM_BLOCK.get(), new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> T6_PANAKEIA_INGOT_BLOCK = ITEMS.register("t6_panakeia_ingot_block",() -> new BlockItem(blocklist.T6_PANAKEIA_INGOT_BLOCK.get(), new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> UNITE_ALLOY_BLOCK = ITEMS.register("unite_alloy_block",() -> new BlockItem(blocklist.UNITE_ALLOY_BLOCK.get(), new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> ALCHEMY_TABLE = ITEMS.register("alchemy_table",() -> new BlockItem(blocklist.ALCHEMY_TABLE.get(), new Item.Properties()));
    public static final RegistryObject<Item> PANAKEIA_REED_T0 = ITEMS.register("panakeia_reed_t0",() -> new BlockItem(blocklist.PANAKEIA_REED_T0.get(), new Item.Properties()));
    public static final RegistryObject<Item> PANAKEIA_REED_T1 = ITEMS.register("panakeia_reed_t1",() -> new BlockItem(blocklist.PANAKEIA_REED_T1.get(), new Item.Properties()));
    public static final RegistryObject<Item> PANAKEIA_REED_T2 = ITEMS.register("panakeia_reed_t2",() -> new BlockItem(blocklist.PANAKEIA_REED_T2.get(), new Item.Properties()));
    public static final RegistryObject<Item> PANAKEIA_REED_T3 = ITEMS.register("panakeia_reed_t3",() -> new BlockItem(blocklist.PANAKEIA_REED_T3.get(), new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> PANAKEIA_REED_T4 = ITEMS.register("panakeia_reed_t4",() -> new BlockItem(blocklist.PANAKEIA_REED_T4.get(), new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> PANAKEIA_REED_T5 = ITEMS.register("panakeia_reed_t5",() -> new BlockItem(blocklist.PANAKEIA_REED_T5.get(), new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> PANAKEIA_REED_T6 = ITEMS.register("panakeia_reed_t6",() -> new BlockItem(blocklist.PANAKEIA_REED_T6.get(), new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> PANAKEIA_REED_T7 = ITEMS.register("panakeia_reed_t7",() -> new BlockItem(blocklist.PANAKEIA_REED_T7.get(), new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> ALCHEMY_INTERMEDIATE_KIT = ITEMS.register("alchemy_intermediate_kit", Alchemy_Intermediate_Kit::new);
    public static final RegistryObject<Item> ALCHEMY_EXPERTS_KIT = ITEMS.register("alchemy_experts_kit", Alchemy_Experts_Kit::new);
    public static final RegistryObject<Item> ULTIMATE_ALCHEMY_KIT = ITEMS.register("ultimate_alchemy_kit", Ultimate_Alchemy_Kit::new);
    public static final RegistryObject<Item> HERMES_WORKBENCH = ITEMS.register("hermes_workbench",() -> new BlockItem(blocklist.HERMES_WORKBENCH.get(), new Item.Properties()));
    public static final RegistryObject<Item> TRANSCENDENTAL_TABLE = ITEMS.register("transcendental_table",() -> new BlockItem(blocklist.TRANSCENDENTAL_TABLE.get(), new Item.Properties()));
    public static final RegistryObject<Item> HIGH_DENSITY_T1_PANAKEIA_INGOT = ITEMS.register("high_density_t1_panakeia_ingot", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> HIGH_DENSITY_T2_PANAKEIA_INGOT = ITEMS.register("high_density_t2_panakeia_ingot", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> HIGH_DENSITY_T3_PANAKEIA_INGOT = ITEMS.register("high_density_t3_panakeia_ingot", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> HIGH_DENSITY_T4_PANAKEIA_GEM = ITEMS.register("high_density_t4_panakeia_gem", UncommonAlchemyMaterial::new);
    public static final RegistryObject<Item> HIGH_DENSITY_T5_PANAKEIA_GEM = ITEMS.register("high_density_t5_panakeia_gem", UncommonAlchemyMaterial::new);
    public static final RegistryObject<Item> HIGH_DENSITY_T6_PANAKEIA_INGOT = ITEMS.register("high_density_t6_panakeia_ingot", RareAlchemyMaterial::new);
    public static final RegistryObject<Item> HIGH_DENSITY_UNITE_ALLOY = ITEMS.register("high_density_unite_alloy", High_Density_Unite_Alloy::new);
    public static final RegistryObject<Item> WISDOM_CRYSTAL = ITEMS.register("wisdom_crystal", Wisdom_Crystal::new);
    public static final RegistryObject<Item> COURAGE_CRYSTAL = ITEMS.register("courage_crystal", Courage_Crystal::new);
    public static final RegistryObject<Item> JUSTICE_CRYSTAL = ITEMS.register("justice_crystal", Justice_Crystal::new);
    public static final RegistryObject<Item> LOVE_CRYSTAL = ITEMS.register("love_crystal", Love_Crystal::new);
    public static final RegistryObject<Item> HOPE_CRYSTAL = ITEMS.register("hope_crystal", Hope_Crystal::new);
    public static final RegistryObject<Item> TEMPERANCE_CRYSTAL = ITEMS.register("temperance_crystal", Temperance_Crystal::new);
    public static final RegistryObject<Item> FAITH_CRYSTAL = ITEMS.register("faith_crystal", Faith_Crystal::new);
    public static final RegistryObject<Item> ORIGIN_OF_WISDOM = ITEMS.register("origin_of_wisdom", Origin_of_Wisdom::new);
    public static final RegistryObject<Item> ORIGIN_OF_COURAGE = ITEMS.register("origin_of_courage", Origin_of_Courage::new);
    public static final RegistryObject<Item> ORIGIN_OF_JUSTICE = ITEMS.register("origin_of_justice", Origin_of_Justice::new);
    public static final RegistryObject<Item> ORIGIN_OF_LOVE = ITEMS.register("origin_of_love", Origin_of_Love::new);
    public static final RegistryObject<Item> ORIGIN_OF_HOPE = ITEMS.register("origin_of_hope", Origin_of_Hope::new);
    public static final RegistryObject<Item> ORIGIN_OF_TEMPERANCE = ITEMS.register("origin_of_temperance", Origin_of_Temperance::new);
    public static final RegistryObject<Item> ORIGIN_OF_FAITH = ITEMS.register("origin_of_faith", Origin_of_Faith::new);
    public static final RegistryObject<Item> BLANK_RUNE = ITEMS.register("blank_rune", Blank_Rune::new);
    public static final RegistryObject<Item> VOID_RUNE = ITEMS.register("void_rune", Void_Rune::new);
    public static final RegistryObject<Item> BASIC_ENGRAVING_INK = ITEMS.register("basic_engraving_ink", Basic_Engraving_Ink::new);
    public static final RegistryObject<Item> ADVANCED_ENGRAVING_INK = ITEMS.register("advanced_engraving_ink", Advanced_Engraving_Ink::new);
    public static final RegistryObject<Item> ELITE_ENGRAVING_INK = ITEMS.register("elite_engraving_ink", Elite_Engraving_Ink::new);
    public static final RegistryObject<Item> ULTIMATE_ENGRAVING_INK = ITEMS.register("ultimate_engraving_ink", Ultimate_Engraving_Ink::new);
    public static final RegistryObject<Item> BASIC_GRINDING_RUNE = ITEMS.register("basic_grinding_rune", Basic_Grinding_Rune::new);
    public static final RegistryObject<Item> ADVANCED_GRINDING_RUNE = ITEMS.register("advanced_grinding_rune", Advanced_Grinding_Rune::new);
    public static final RegistryObject<Item> ELITE_GRINDING_RUNE = ITEMS.register("elite_grinding_rune", Elite_Grinding_Rune::new);
    public static final RegistryObject<Item> ULTIMATE_GRINDING_RUNE = ITEMS.register("ultimate_grinding_rune", Ultimate_Grinding_Rune::new);
    public static final RegistryObject<Item> BASIC_GRANULATING_RUNE = ITEMS.register("basic_granulating_rune", Basic_Granulating_Rune::new);
    public static final RegistryObject<Item> ADVANCED_GRANULATING_RUNE = ITEMS.register("advanced_granulating_rune", Advanced_Granulating_Rune::new);
    public static final RegistryObject<Item> ELITE_GRANULATING_RUNE = ITEMS.register("elite_granulating_rune", Elite_Granulating_Rune::new);
    public static final RegistryObject<Item> ULTIMATE_GRANULATING_RUNE = ITEMS.register("ultimate_granulating_rune", Ultimate_Granulating_Rune::new);
    public static final RegistryObject<Item> BASIC_SOFTENING_RUNE = ITEMS.register("basic_softening_rune", Basic_Softening_Rune::new);
    public static final RegistryObject<Item> ADVANCED_SOFTENING_RUNE = ITEMS.register("advanced_softening_rune", Advanced_Softening_Rune::new);
    public static final RegistryObject<Item> ELITE_SOFTENING_RUNE = ITEMS.register("elite_softening_rune", Elite_Softening_Rune::new);
    public static final RegistryObject<Item> ULTIMATE_SOFTENING_RUNE = ITEMS.register("ultimate_softening_rune", Ultimate_Softening_Rune::new);
    public static final RegistryObject<Item> BASIC_PURIFICATION_RUNE = ITEMS.register("basic_purification_rune", Basic_Purification_Rune::new);
    public static final RegistryObject<Item> ADVANCED_PURIFICATION_RUNE = ITEMS.register("advanced_purification_rune", Advanced_Purification_Rune::new);
    public static final RegistryObject<Item> ELITE_PURIFICATION_RUNE = ITEMS.register("elite_purification_rune", Basic_Purification_Rune::new);
    public static final RegistryObject<Item> ULTIMATE_PURIFICATION_RUNE = ITEMS.register("ultimate_purification_rune", Ultimate_Purification_Rune::new);
    public static final RegistryObject<Item> CRUSHED_RAW_COPPER = ITEMS.register("crushed_raw_copper", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> CRUSHED_RAW_IRON = ITEMS.register("crushed_raw_iron", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> CRUSHED_RAW_GOLD = ITEMS.register("crushed_raw_gold", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> CRUSHED_DIAMOND_ORE = ITEMS.register("crushed_diamond_ore", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> CRUSHED_EMERALD_ORE = ITEMS.register("crushed_emerald_ore", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> CRUSHED_ANCIENT_DEBRIS = ITEMS.register("crushed_ancient_debris", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> GRANULATED_COPPER = ITEMS.register("granulated_copper", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> GRANULATED_IRON = ITEMS.register("granulated_iron", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> GRANULATED_GOLD = ITEMS.register("granulated_gold", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> GRANULATED_DIAMOND = ITEMS.register("granulated_diamond", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> GRANULATED_EMERALD = ITEMS.register("granulated_emerald", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> GRANULATED_ANCIENT_DEBRIS = ITEMS.register("granulated_ancient_debris", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> SOFTENED_COPPER = ITEMS.register("softened_copper", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> SOFTENED_IRON = ITEMS.register("softened_iron", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> SOFTENED_GOLD = ITEMS.register("softened_gold", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> SOFTENED_DIAMOND = ITEMS.register("softened_diamond", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> SOFTENED_EMERALD = ITEMS.register("softened_emerald", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> SOFTENED_ANCIENT_DEBRIS = ITEMS.register("softened_ancient_debris", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> PURIFIED_COPPER = ITEMS.register("purified_copper", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> PURIFIED_IRON = ITEMS.register("purified_iron", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> PURIFIED_GOLD = ITEMS.register("purified_gold", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> PURIFIED_DIAMOND = ITEMS.register("purified_diamond", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> PURIFIED_EMERALD = ITEMS.register("purified_emerald", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> PURIFIED_ANCIENT_DEBRIS = ITEMS.register("purified_ancient_debris", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> ALCHEMICAL_ENGRAVER = ITEMS.register("alchemical_engraver",() -> new BlockItem(blocklist.ALCHEMICAL_ENGRAVER.get(), new Item.Properties()));
    public static final RegistryObject<Item> RUNE_ACTIVATOR = ITEMS.register("rune_activator",() -> new BlockItem(blocklist.RUNE_ACTIVATOR.get(), new Item.Properties()));
    public static final RegistryObject<Item> X9_COBBLESTONE = ITEMS.register("x9_cobblestone",() -> new BlockItem(blocklist.X9_COBBLESTONE.get(), new Item.Properties()));
    public static final RegistryObject<Item> X225_COBBLESTONE = ITEMS.register("x225_cobblestone",() -> new BlockItem(blocklist.X225_COBBLESTONE.get(), new Item.Properties()));
    public static final RegistryObject<Item> X38025_COBBLESTONE = ITEMS.register("x38025_cobblestone",() -> new BlockItem(blocklist.X38025_COBBLESTONE.get(), new Item.Properties()));
    public static final RegistryObject<Item> IMITATED_BEDROCK = ITEMS.register("imitated_bedrock",() -> new BlockItem(blocklist.IMITATED_BEDROCK.get(), new Item.Properties()));
    public static final RegistryObject<Item> PHILOSOPHERS_STONE = ITEMS.register("philosophers_stone", Philosophers_stone::new);
    public static final RegistryObject<Item> ARCANE_STAR = ITEMS.register("arcane_star", Arcane_Star::new);
    public static final RegistryObject<Item> ARCANE_DRAGON_EGG = ITEMS.register("arcane_dragon_egg", Arcane_Dragon_Egg::new);
    public static final RegistryObject<Item> SINGULARITY = ITEMS.register("singularity", Singularity::new);
    public static final RegistryObject<Item> T1_COMBUSTION_RUNE = ITEMS.register("t1_combustion_rune",() -> new FuelItem(new Item.Properties().rarity(Rarity.COMMON),2400));
    public static final RegistryObject<Item> T2_COMBUSTION_RUNE = ITEMS.register("t2_combustion_rune",() -> new FuelItem(new Item.Properties().rarity(Rarity.COMMON),3600));
    public static final RegistryObject<Item> T3_COMBUSTION_RUNE = ITEMS.register("t3_combustion_rune",() -> new FuelItem(new Item.Properties().rarity(Rarity.UNCOMMON),5400));
    public static final RegistryObject<Item> T4_COMBUSTION_RUNE = ITEMS.register("t4_combustion_rune",() -> new FuelItem(new Item.Properties().rarity(Rarity.UNCOMMON),8100));
    public static final RegistryObject<Item> T5_COMBUSTION_RUNE = ITEMS.register("t5_combustion_rune",() -> new FuelItem(new Item.Properties().rarity(Rarity.RARE),12150));
    public static final RegistryObject<Item> T6_COMBUSTION_RUNE = ITEMS.register("t6_combustion_rune",() -> new FuelItem(new Item.Properties().rarity(Rarity.RARE),18225));
    public static final RegistryObject<Item> SEMI_ETERNAL_FUEL = ITEMS.register("semi_eternal_fuel",Semi_Eternal_Fuel::new);
    public static final RegistryObject<Item> ETERNAL_FUEL = ITEMS.register("eternal_fuel", Eternal_Fuel::new);
    public static final RegistryObject<Item> T1_COMBUSTION_RUNE_BLOCK = ITEMS.register("t1_combustion_rune_block",() -> new BlockItem(blocklist.T1_COMBUSTION_RUNE_BLOCK.get(), new Item.Properties()));
    public static final RegistryObject<Item> T2_COMBUSTION_RUNE_BLOCK = ITEMS.register("t2_combustion_rune_block",() -> new BlockItem(blocklist.T2_COMBUSTION_RUNE_BLOCK.get(), new Item.Properties()));
    public static final RegistryObject<Item> T3_COMBUSTION_RUNE_BLOCK = ITEMS.register("t3_combustion_rune_block",() -> new BlockItem(blocklist.T3_COMBUSTION_RUNE_BLOCK.get(), new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> T4_COMBUSTION_RUNE_BLOCK = ITEMS.register("t4_combustion_rune_block",() -> new BlockItem(blocklist.T4_COMBUSTION_RUNE_BLOCK.get(), new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> T5_COMBUSTION_RUNE_BLOCK = ITEMS.register("t5_combustion_rune_block",() -> new BlockItem(blocklist.T5_COMBUSTION_RUNE_BLOCK.get(), new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> T6_COMBUSTION_RUNE_BLOCK = ITEMS.register("t6_combustion_rune_block",() -> new BlockItem(blocklist.T6_COMBUSTION_RUNE_BLOCK.get(), new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> T1_PANAKEIA_PICKAXE = ITEMS.register("t1_panakeia_pickaxe",() -> Panakeia_Pickaxes.T1_PANAKEIA_PICKAXE);
    public static final RegistryObject<Item> T2_PANAKEIA_PICKAXE = ITEMS.register("t2_panakeia_pickaxe",() -> Panakeia_Pickaxes.T2_PANAKEIA_PICKAXE);
    public static final RegistryObject<Item> T3_PANAKEIA_PICKAXE = ITEMS.register("t3_panakeia_pickaxe",() -> Panakeia_Pickaxes.T3_PANAKEIA_PICKAXE);
    public static final RegistryObject<Item> T4_PANAKEIA_PICKAXE = ITEMS.register("t4_panakeia_pickaxe",() -> Panakeia_Pickaxes.T4_PANAKEIA_PICKAXE);
    public static final RegistryObject<Item> T5_PANAKEIA_PICKAXE = ITEMS.register("t5_panakeia_pickaxe",() -> Panakeia_Pickaxes.T5_PANAKEIA_PICKAXE);
    public static final RegistryObject<Item> T6_PANAKEIA_PICKAXE = ITEMS.register("t6_panakeia_pickaxe",() -> Panakeia_Pickaxes.T6_PANAKEIA_PICKAXE);
    public static final RegistryObject<Item> UNITE_ALLOY_PICKAXE = ITEMS.register("unite_alloy_pickaxe",() -> Panakeia_Pickaxes.UNITE_ALLOY_PICKAXE);
    public static final RegistryObject<Item> T1_PANAKEIA_SHOVEL = ITEMS.register("t1_panakeia_shovel",() -> Panakeia_Shovels.T1_PANAKEIA_SHOVEL);
    public static final RegistryObject<Item> T2_PANAKEIA_SHOVEL = ITEMS.register("t2_panakeia_shovel",() -> Panakeia_Shovels.T2_PANAKEIA_SHOVEL);
    public static final RegistryObject<Item> T3_PANAKEIA_SHOVEL = ITEMS.register("t3_panakeia_shovel",() -> Panakeia_Shovels.T3_PANAKEIA_SHOVEL);
    public static final RegistryObject<Item> T4_PANAKEIA_SHOVEL = ITEMS.register("t4_panakeia_shovel",() -> Panakeia_Shovels.T4_PANAKEIA_SHOVEL);
    public static final RegistryObject<Item> T5_PANAKEIA_SHOVEL = ITEMS.register("t5_panakeia_shovel",() -> Panakeia_Shovels.T5_PANAKEIA_SHOVEL);
    public static final RegistryObject<Item> T6_PANAKEIA_SHOVEL = ITEMS.register("t6_panakeia_shovel",() -> Panakeia_Shovels.T6_PANAKEIA_SHOVEL);
    public static final RegistryObject<Item> UNITE_ALLOY_SHOVEL = ITEMS.register("unite_alloy_shovel",() -> Panakeia_Shovels.UNITE_ALLOY_SHOVEL);
    public static final RegistryObject<Item> T1_PANAKEIA_AXE = ITEMS.register("t1_panakeia_axe",() -> Panakeia_Axes.T1_PANAKEIA_AXE);
    public static final RegistryObject<Item> T2_PANAKEIA_AXE = ITEMS.register("t2_panakeia_axe",() -> Panakeia_Axes.T2_PANAKEIA_AXE);
    public static final RegistryObject<Item> T3_PANAKEIA_AXE = ITEMS.register("t3_panakeia_axe",() -> Panakeia_Axes.T3_PANAKEIA_AXE);
    public static final RegistryObject<Item> T4_PANAKEIA_AXE = ITEMS.register("t4_panakeia_axe",() -> Panakeia_Axes.T4_PANAKEIA_AXE);
    public static final RegistryObject<Item> T5_PANAKEIA_AXE = ITEMS.register("t5_panakeia_axe",() -> Panakeia_Axes.T5_PANAKEIA_AXE);
    public static final RegistryObject<Item> T6_PANAKEIA_AXE = ITEMS.register("t6_panakeia_axe",() -> Panakeia_Axes.T6_PANAKEIA_AXE);
    public static final RegistryObject<Item> UNITE_ALLOY_AXE = ITEMS.register("unite_alloy_axe",() -> Panakeia_Axes.UNITE_ALLOY_AXE);
    public static final RegistryObject<Item> T1_PANAKEIA_HOE = ITEMS.register("t1_panakeia_hoe",() -> Panakeia_Hoes.T1_PANAKEIA_HOE);
    public static final RegistryObject<Item> T2_PANAKEIA_HOE = ITEMS.register("t2_panakeia_hoe",() -> Panakeia_Hoes.T2_PANAKEIA_HOE);
    public static final RegistryObject<Item> T3_PANAKEIA_HOE = ITEMS.register("t3_panakeia_hoe",() -> Panakeia_Hoes.T3_PANAKEIA_HOE);
    public static final RegistryObject<Item> T4_PANAKEIA_HOE = ITEMS.register("t4_panakeia_hoe",() -> Panakeia_Hoes.T4_PANAKEIA_HOE);
    public static final RegistryObject<Item> T5_PANAKEIA_HOE = ITEMS.register("t5_panakeia_hoe",() -> Panakeia_Hoes.T5_PANAKEIA_HOE);
    public static final RegistryObject<Item> T6_PANAKEIA_HOE = ITEMS.register("t6_panakeia_hoe",() -> Panakeia_Hoes.T6_PANAKEIA_HOE);
    public static final RegistryObject<Item> UNITE_ALLOY_HOE = ITEMS.register("unite_alloy_hoe",() -> Panakeia_Hoes.UNITE_ALLOY_HOE);
    public static final RegistryObject<Item> T1_PANAKEIA_SWORD = ITEMS.register("t1_panakeia_sword",() -> Panakeia_Swords.T1_PANAKEIA_SWORD);
    public static final RegistryObject<Item> T2_PANAKEIA_SWORD = ITEMS.register("t2_panakeia_sword",() -> Panakeia_Swords.T2_PANAKEIA_SWORD);
    public static final RegistryObject<Item> T3_PANAKEIA_SWORD = ITEMS.register("t3_panakeia_sword",() -> Panakeia_Swords.T3_PANAKEIA_SWORD);
    public static final RegistryObject<Item> T4_PANAKEIA_SWORD = ITEMS.register("t4_panakeia_sword",() -> Panakeia_Swords.T4_PANAKEIA_SWORD);
    public static final RegistryObject<Item> T5_PANAKEIA_SWORD = ITEMS.register("t5_panakeia_sword",() -> Panakeia_Swords.T5_PANAKEIA_SWORD);
    public static final RegistryObject<Item> T6_PANAKEIA_SWORD = ITEMS.register("t6_panakeia_sword",() -> Panakeia_Swords.T6_PANAKEIA_SWORD);
    public static final RegistryObject<Item> UNITE_ALLOY_SWORD = ITEMS.register("unite_alloy_sword",() -> Panakeia_Swords.UNITE_ALLOY_SWORD);
    public static final RegistryObject<Item> T1_PANAKEIA_CUBE = ITEMS.register("t1_panakeia_cube",CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> T2_PANAKEIA_CUBE = ITEMS.register("t2_panakeia_cube",CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> T3_PANAKEIA_CUBE = ITEMS.register("t3_panakeia_cube",CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> T4_PANAKEIA_CUBE = ITEMS.register("t4_panakeia_cube",UncommonAlchemyMaterial::new);
    public static final RegistryObject<Item> T5_PANAKEIA_CUBE = ITEMS.register("t5_panakeia_cube",UncommonAlchemyMaterial::new);
    public static final RegistryObject<Item> T6_PANAKEIA_CUBE = ITEMS.register("t6_panakeia_cube",RareAlchemyMaterial::new);
    public static final RegistryObject<Item> T7_PANAKEIA_CUBE = ITEMS.register("t7_panakeia_cube",EpicAlchemyMaterial::new);
    public static final RegistryObject<Item> T1_PANAKEIA_HELMET = ITEMS.register("t1_panakeia_helmet",() -> Panakeia_Armors.T1_PANAKEIA_HELMET);
    public static final RegistryObject<Item> T1_PANAKEIA_CHESTPLATE = ITEMS.register("t1_panakeia_chestplate",() -> Panakeia_Armors.T1_PANAKEIA_CHESTPLATE);
    public static final RegistryObject<Item> T1_PANAKEIA_LEGGINGS = ITEMS.register("t1_panakeia_leggings",() -> Panakeia_Armors.T1_PANAKEIA_LEGGINGS);
    public static final RegistryObject<Item> T1_PANAKEIA_BOOTS = ITEMS.register("t1_panakeia_boots",() -> Panakeia_Armors.T1_PANAKEIA_BOOTS);
    public static final RegistryObject<Item> T2_PANAKEIA_HELMET = ITEMS.register("t2_panakeia_helmet",() -> Panakeia_Armors.T2_PANAKEIA_HELMET);
    public static final RegistryObject<Item> T2_PANAKEIA_CHESTPLATE = ITEMS.register("t2_panakeia_chestplate",() -> Panakeia_Armors.T2_PANAKEIA_CHESTPLATE);
    public static final RegistryObject<Item> T2_PANAKEIA_LEGGINGS = ITEMS.register("t2_panakeia_leggings",() -> Panakeia_Armors.T2_PANAKEIA_LEGGINGS);
    public static final RegistryObject<Item> T2_PANAKEIA_BOOTS = ITEMS.register("t2_panakeia_boots",() -> Panakeia_Armors.T2_PANAKEIA_BOOTS);
    public static final RegistryObject<Item> T3_PANAKEIA_HELMET = ITEMS.register("t3_panakeia_helmet",() -> Panakeia_Armors.T3_PANAKEIA_HELMET);
    public static final RegistryObject<Item> T3_PANAKEIA_CHESTPLATE = ITEMS.register("t3_panakeia_chestplate",() -> Panakeia_Armors.T3_PANAKEIA_CHESTPLATE);
    public static final RegistryObject<Item> T3_PANAKEIA_LEGGINGS = ITEMS.register("t3_panakeia_leggings",() -> Panakeia_Armors.T3_PANAKEIA_LEGGINGS);
    public static final RegistryObject<Item> T3_PANAKEIA_BOOTS = ITEMS.register("t3_panakeia_boots",() -> Panakeia_Armors.T3_PANAKEIA_BOOTS);
    public static final RegistryObject<Item> T4_PANAKEIA_HELMET = ITEMS.register("t4_panakeia_helmet",() -> Panakeia_Armors.T4_PANAKEIA_HELMET);
    public static final RegistryObject<Item> T4_PANAKEIA_CHESTPLATE = ITEMS.register("t4_panakeia_chestplate",() -> Panakeia_Armors.T4_PANAKEIA_CHESTPLATE);
    public static final RegistryObject<Item> T4_PANAKEIA_LEGGINGS = ITEMS.register("t4_panakeia_leggings",() -> Panakeia_Armors.T4_PANAKEIA_LEGGINGS);
    public static final RegistryObject<Item> T4_PANAKEIA_BOOTS = ITEMS.register("t4_panakeia_boots",() -> Panakeia_Armors.T4_PANAKEIA_BOOTS);
    public static final RegistryObject<Item> T5_PANAKEIA_HELMET = ITEMS.register("t5_panakeia_helmet",() -> Panakeia_Armors.T5_PANAKEIA_HELMET);
    public static final RegistryObject<Item> T5_PANAKEIA_CHESTPLATE = ITEMS.register("t5_panakeia_chestplate",() -> Panakeia_Armors.T5_PANAKEIA_CHESTPLATE);
    public static final RegistryObject<Item> T5_PANAKEIA_LEGGINGS = ITEMS.register("t5_panakeia_leggings",() -> Panakeia_Armors.T5_PANAKEIA_LEGGINGS);
    public static final RegistryObject<Item> T5_PANAKEIA_BOOTS = ITEMS.register("t5_panakeia_boots",() -> Panakeia_Armors.T5_PANAKEIA_BOOTS);
    public static final RegistryObject<Item> T6_PANAKEIA_HELMET = ITEMS.register("t6_panakeia_helmet",() -> Panakeia_Armors.T6_PANAKEIA_HELMET);
    public static final RegistryObject<Item> T6_PANAKEIA_CHESTPLATE = ITEMS.register("t6_panakeia_chestplate",() -> Panakeia_Armors.T6_PANAKEIA_CHESTPLATE);
    public static final RegistryObject<Item> T6_PANAKEIA_LEGGINGS = ITEMS.register("t6_panakeia_leggings",() -> Panakeia_Armors.T6_PANAKEIA_LEGGINGS);
    public static final RegistryObject<Item> T6_PANAKEIA_BOOTS = ITEMS.register("t6_panakeia_boots",() -> Panakeia_Armors.T6_PANAKEIA_BOOTS);
    public static final RegistryObject<Item> UNITE_ALLOY_HELMET = ITEMS.register("unite_alloy_helmet",() -> Panakeia_Armors.UNITE_ALLOY_HELMET);
    public static final RegistryObject<Item> UNITE_ALLOY_CHESTPLATE = ITEMS.register("unite_alloy_chestplate",() -> Panakeia_Armors.UNITE_ALLOY_CHESTPLATE);
    public static final RegistryObject<Item> UNITE_ALLOY_LEGGINGS = ITEMS.register("unite_alloy_leggings",() -> Panakeia_Armors.UNITE_ALLOY_LEGGINGS);
    public static final RegistryObject<Item> UNITE_ALLOY_BOOTS = ITEMS.register("unite_alloy_boots",() -> Panakeia_Armors.UNITE_ALLOY_BOOTS);
    public static final RegistryObject<Item> THE_DESTROYER_OF_THE_RIAL = ITEMS.register("the_destroyer_of_the_rial",The_Destroyer_of_the_Rial::new);
    public static final RegistryObject<Item> ANGEL_RING = ITEMS.register("angel_ring",Angel_Ring::new);

    //アイテムリストの登録用
    public static void register(IEventBus eventBus){
        ITEMS.register(eventBus);
    }
}
