package jp.nogami_rion.alchemical_power.init;


import jp.nogami_rion.alchemical_power.Alchemical_power;
import jp.nogami_rion.alchemical_power.block.custom.ModLeavesBlock;
import jp.nogami_rion.alchemical_power.item.*;
import jp.nogami_rion.alchemical_power.item.accessory.Alchemists_ring;
import jp.nogami_rion.alchemical_power.item.accessory.Gluttonys_ring;
import jp.nogami_rion.alchemical_power.item.accessory.Greed_Ring;
import jp.nogami_rion.alchemical_power.item.baseclass.*;
import jp.nogami_rion.alchemical_power.item.custom.FuelItem;
import jp.nogami_rion.alchemical_power.item.food.Steaves_Lava_Chicken;
import jp.nogami_rion.alchemical_power.item.materials.*;
import jp.nogami_rion.alchemical_power.item.rune.*;
import net.minecraft.world.item.*;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class itemlist {
    //アイテムリストを生成
    private static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, Alchemical_power.MODID);
    public static final RegistryObject<Item> T0_PANAKEIA = ITEMS.register("t0_panakeia", T0_Panakeia::new);
    public static final RegistryObject<Item> T1_PANAKEIA = ITEMS.register("t1_panakeia", T1_Panakeia::new);
    public static final RegistryObject<Item> T2_PANAKEIA = ITEMS.register("t2_panakeia", T2_Panakeia::new);
    public static final RegistryObject<Item> T3_PANAKEIA = ITEMS.register("t3_panakeia", T3_Panakeia::new);
    public static final RegistryObject<Item> T4_PANAKEIA = ITEMS.register("t4_panakeia", T4_Panakeia::new);
    public static final RegistryObject<Item> T5_PANAKEIA = ITEMS.register("t5_panakeia", T5_Panakeia::new);
    public static final RegistryObject<Item> T6_PANAKEIA = ITEMS.register("t6_panakeia", T6_Panakeia::new);
    public static final RegistryObject<Item> T7_PANAKEIA = ITEMS.register("t7_panakeia", T7_Panakeia::new);
    public static final RegistryObject<Item> PANAKEIA_BEARING_STONE = ITEMS.register("panakeia_bearing_stone",() -> new BlockItem(blocklist.PANAKEIA_BEARING_STONE.get(), new Item.Properties()));
    public static final RegistryObject<Item> ALCHEMY_BEGINNERS_KIT = ITEMS.register("alchemy_beginners_kit",Alchemy_Bginners_Kit::new);
    public static final RegistryObject<Item> T1_PANAKEIA_INGOT = ITEMS.register("t1_panakeia_ingot",CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> T2_PANAKEIA_INGOT = ITEMS.register("t2_panakeia_ingot",CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> T3_PANAKEIA_INGOT = ITEMS.register("t3_panakeia_ingot", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> T4_PANAKEIA_GEM = ITEMS.register("t4_panakeia_gem", UncommonAlchemyMaterial::new);
    public static final RegistryObject<Item> T5_PANAKEIA_GEM = ITEMS.register("t5_panakeia_gem", UncommonAlchemyMaterial::new);
    public static final RegistryObject<Item> T6_PANAKEIA_INGOT = ITEMS.register("t6_panakeia_ingot", RareAlchemyMaterial::new);
    public static final RegistryObject<Item> UNITE_ALLOY = ITEMS.register("unite_alloy", Unite_Alloy::new);
    public static final RegistryObject<Item> T1_PANAKEIA_INGOT_BLOCK = ITEMS.register("t1_panakeia_ingot_block",() -> new BlockItem(blocklist.T1_PANAKEIA_INGOT_BLOCK.get(), new Item.Properties()));
    public static final RegistryObject<Item> T2_PANAKEIA_INGOT_BLOCK = ITEMS.register("t2_panakeia_ingot_block",() -> new BlockItem(blocklist.T2_PANAKEIA_INGOT_BLOCK.get(), new Item.Properties()));
    public static final RegistryObject<Item> T3_PANAKEIA_INGOT_BLOCK = ITEMS.register("t3_panakeia_ingot_block",() -> new BlockItem(blocklist.T3_PANAKEIA_INGOT_BLOCK.get(), new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> T4_PANAKEIA_GEM_BLOCK = ITEMS.register("t4_panakeia_gem_block",() -> new BlockItem(blocklist.T4_PANAKEIA_GEM_BLOCK.get(), new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> T5_PANAKEIA_GEM_BLOCK = ITEMS.register("t5_panakeia_gem_block",() -> new BlockItem(blocklist.T5_PANAKEIA_GEM_BLOCK.get(), new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> T6_PANAKEIA_INGOT_BLOCK = ITEMS.register("t6_panakeia_ingot_block",() -> new BlockItem(blocklist.T6_PANAKEIA_INGOT_BLOCK.get(), new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> UNITE_ALLOY_BLOCK = ITEMS.register("unite_alloy_block",() -> new BlockItem(blocklist.UNITE_ALLOY_BLOCK.get(), new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> ALCHEMY_TABLE = ITEMS.register("alchemy_table",() -> new BlockItem(blocklist.ALCHEMY_TABLE.get(), new Item.Properties()));
    public static final RegistryObject<Item> PANAKEIA_REED_T0 = ITEMS.register("panakeia_reed_t0",() -> new BlockItem(blocklist.PANAKEIA_REED_T0.get(), new Item.Properties()));
    public static final RegistryObject<Item> PANAKEIA_REED_T1 = ITEMS.register("panakeia_reed_t1",() -> new BlockItem(blocklist.PANAKEIA_REED_T1.get(), new Item.Properties()));
    public static final RegistryObject<Item> PANAKEIA_REED_T2 = ITEMS.register("panakeia_reed_t2",() -> new BlockItem(blocklist.PANAKEIA_REED_T2.get(), new Item.Properties()));
    public static final RegistryObject<Item> PANAKEIA_REED_T3 = ITEMS.register("panakeia_reed_t3",() -> new BlockItem(blocklist.PANAKEIA_REED_T3.get(), new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> PANAKEIA_REED_T4 = ITEMS.register("panakeia_reed_t4",() -> new BlockItem(blocklist.PANAKEIA_REED_T4.get(), new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> PANAKEIA_REED_T5 = ITEMS.register("panakeia_reed_t5",() -> new BlockItem(blocklist.PANAKEIA_REED_T5.get(), new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> PANAKEIA_REED_T6 = ITEMS.register("panakeia_reed_t6",() -> new BlockItem(blocklist.PANAKEIA_REED_T6.get(), new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> PANAKEIA_REED_T7 = ITEMS.register("panakeia_reed_t7",() -> new BlockItem(blocklist.PANAKEIA_REED_T7.get(), new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> ALCHEMY_INTERMEDIATE_KIT = ITEMS.register("alchemy_intermediate_kit", Alchemy_Intermediate_Kit::new);
    public static final RegistryObject<Item> ALCHEMY_EXPERTS_KIT = ITEMS.register("alchemy_experts_kit", Alchemy_Experts_Kit::new);
    public static final RegistryObject<Item> ULTIMATE_ALCHEMY_KIT = ITEMS.register("ultimate_alchemy_kit", Ultimate_Alchemy_Kit::new);
    public static final RegistryObject<Item> HERMES_WORKBENCH = ITEMS.register("hermes_workbench",() -> new BlockItem(blocklist.HERMES_WORKBENCH.get(), new Item.Properties()));
    public static final RegistryObject<Item> TRANSCENDENTAL_TABLE = ITEMS.register("transcendental_table",() -> new BlockItem(blocklist.TRANSCENDENTAL_TABLE.get(), new Item.Properties()));
    public static final RegistryObject<Item> HIGH_DENSITY_T1_PANAKEIA_INGOT = ITEMS.register("high_density_t1_panakeia_ingot", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> HIGH_DENSITY_T2_PANAKEIA_INGOT = ITEMS.register("high_density_t2_panakeia_ingot", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> HIGH_DENSITY_T3_PANAKEIA_INGOT = ITEMS.register("high_density_t3_panakeia_ingot", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> HIGH_DENSITY_T4_PANAKEIA_GEM = ITEMS.register("high_density_t4_panakeia_gem", UncommonAlchemyMaterial::new);
    public static final RegistryObject<Item> HIGH_DENSITY_T5_PANAKEIA_GEM = ITEMS.register("high_density_t5_panakeia_gem", UncommonAlchemyMaterial::new);
    public static final RegistryObject<Item> HIGH_DENSITY_T6_PANAKEIA_INGOT = ITEMS.register("high_density_t6_panakeia_ingot", RareAlchemyMaterial::new);
    public static final RegistryObject<Item> HIGH_DENSITY_UNITE_ALLOY = ITEMS.register("high_density_unite_alloy", High_Density_Unite_Alloy::new);
    public static final RegistryObject<Item> WISDOM_CRYSTAL = ITEMS.register("wisdom_crystal", Wisdom_Crystal::new);
    public static final RegistryObject<Item> COURAGE_CRYSTAL = ITEMS.register("courage_crystal", Courage_Crystal::new);
    public static final RegistryObject<Item> JUSTICE_CRYSTAL = ITEMS.register("justice_crystal", Justice_Crystal::new);
    public static final RegistryObject<Item> LOVE_CRYSTAL = ITEMS.register("love_crystal", Love_Crystal::new);
    public static final RegistryObject<Item> HOPE_CRYSTAL = ITEMS.register("hope_crystal", Hope_Crystal::new);
    public static final RegistryObject<Item> TEMPERANCE_CRYSTAL = ITEMS.register("temperance_crystal", Temperance_Crystal::new);
    public static final RegistryObject<Item> FAITH_CRYSTAL = ITEMS.register("faith_crystal", Faith_Crystal::new);
    public static final RegistryObject<Item> ORIGIN_OF_WISDOM = ITEMS.register("origin_of_wisdom", Origin_of_Wisdom::new);
    public static final RegistryObject<Item> ORIGIN_OF_COURAGE = ITEMS.register("origin_of_courage", Origin_of_Courage::new);
    public static final RegistryObject<Item> ORIGIN_OF_JUSTICE = ITEMS.register("origin_of_justice", Origin_of_Justice::new);
    public static final RegistryObject<Item> ORIGIN_OF_LOVE = ITEMS.register("origin_of_love", Origin_of_Love::new);
    public static final RegistryObject<Item> ORIGIN_OF_HOPE = ITEMS.register("origin_of_hope", Origin_of_Hope::new);
    public static final RegistryObject<Item> ORIGIN_OF_TEMPERANCE = ITEMS.register("origin_of_temperance", Origin_of_Temperance::new);
    public static final RegistryObject<Item> ORIGIN_OF_FAITH = ITEMS.register("origin_of_faith", Origin_of_Faith::new);
    public static final RegistryObject<Item> BLANK_RUNE = ITEMS.register("blank_rune", Blank_Rune::new);
    public static final RegistryObject<Item> VOID_RUNE = ITEMS.register("void_rune", Void_Rune::new);
    public static final RegistryObject<Item> BASIC_ENGRAVING_INK = ITEMS.register("basic_engraving_ink", Basic_Engraving_Ink::new);
    public static final RegistryObject<Item> ADVANCED_ENGRAVING_INK = ITEMS.register("advanced_engraving_ink", Advanced_Engraving_Ink::new);
    public static final RegistryObject<Item> ELITE_ENGRAVING_INK = ITEMS.register("elite_engraving_ink", Elite_Engraving_Ink::new);
    public static final RegistryObject<Item> ULTIMATE_ENGRAVING_INK = ITEMS.register("ultimate_engraving_ink", Ultimate_Engraving_Ink::new);
    public static final RegistryObject<Item> BASIC_GRINDING_RUNE = ITEMS.register("basic_grinding_rune", Basic_Grinding_Rune::new);
    public static final RegistryObject<Item> ADVANCED_GRINDING_RUNE = ITEMS.register("advanced_grinding_rune", Advanced_Grinding_Rune::new);
    public static final RegistryObject<Item> ELITE_GRINDING_RUNE = ITEMS.register("elite_grinding_rune", Elite_Grinding_Rune::new);
    public static final RegistryObject<Item> ULTIMATE_GRINDING_RUNE = ITEMS.register("ultimate_grinding_rune", Ultimate_Grinding_Rune::new);
    public static final RegistryObject<Item> BASIC_GRANULATING_RUNE = ITEMS.register("basic_granulating_rune", Basic_Granulating_Rune::new);
    public static final RegistryObject<Item> ADVANCED_GRANULATING_RUNE = ITEMS.register("advanced_granulating_rune", Advanced_Granulating_Rune::new);
    public static final RegistryObject<Item> ELITE_GRANULATING_RUNE = ITEMS.register("elite_granulating_rune", Elite_Granulating_Rune::new);
    public static final RegistryObject<Item> ULTIMATE_GRANULATING_RUNE = ITEMS.register("ultimate_granulating_rune", Ultimate_Granulating_Rune::new);
    public static final RegistryObject<Item> BASIC_SOFTENING_RUNE = ITEMS.register("basic_softening_rune", Basic_Softening_Rune::new);
    public static final RegistryObject<Item> ADVANCED_SOFTENING_RUNE = ITEMS.register("advanced_softening_rune", Advanced_Softening_Rune::new);
    public static final RegistryObject<Item> ELITE_SOFTENING_RUNE = ITEMS.register("elite_softening_rune", Elite_Softening_Rune::new);
    public static final RegistryObject<Item> ULTIMATE_SOFTENING_RUNE = ITEMS.register("ultimate_softening_rune", Ultimate_Softening_Rune::new);
    public static final RegistryObject<Item> BASIC_PURIFICATION_RUNE = ITEMS.register("basic_purification_rune", Basic_Purification_Rune::new);
    public static final RegistryObject<Item> ADVANCED_PURIFICATION_RUNE = ITEMS.register("advanced_purification_rune", Advanced_Purification_Rune::new);
    public static final RegistryObject<Item> ELITE_PURIFICATION_RUNE = ITEMS.register("elite_purification_rune", Elite_Purification_Rune::new);
    public static final RegistryObject<Item> ULTIMATE_PURIFICATION_RUNE = ITEMS.register("ultimate_purification_rune", Ultimate_Purification_Rune::new);
    public static final RegistryObject<Item> CRUSHED_RAW_COPPER = ITEMS.register("crushed_raw_copper", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> CRUSHED_RAW_IRON = ITEMS.register("crushed_raw_iron", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> CRUSHED_RAW_GOLD = ITEMS.register("crushed_raw_gold", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> CRUSHED_DIAMOND_ORE = ITEMS.register("crushed_diamond_ore", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> CRUSHED_EMERALD_ORE = ITEMS.register("crushed_emerald_ore", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> CRUSHED_ANCIENT_DEBRIS = ITEMS.register("crushed_ancient_debris", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> GRANULATED_COPPER = ITEMS.register("granulated_copper", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> GRANULATED_IRON = ITEMS.register("granulated_iron", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> GRANULATED_GOLD = ITEMS.register("granulated_gold", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> GRANULATED_DIAMOND = ITEMS.register("granulated_diamond", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> GRANULATED_EMERALD = ITEMS.register("granulated_emerald", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> GRANULATED_ANCIENT_DEBRIS = ITEMS.register("granulated_ancient_debris", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> SOFTENED_COPPER = ITEMS.register("softened_copper", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> SOFTENED_IRON = ITEMS.register("softened_iron", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> SOFTENED_GOLD = ITEMS.register("softened_gold", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> SOFTENED_DIAMOND = ITEMS.register("softened_diamond", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> SOFTENED_EMERALD = ITEMS.register("softened_emerald", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> SOFTENED_ANCIENT_DEBRIS = ITEMS.register("softened_ancient_debris", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> PURIFIED_COPPER = ITEMS.register("purified_copper", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> PURIFIED_IRON = ITEMS.register("purified_iron", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> PURIFIED_GOLD = ITEMS.register("purified_gold", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> PURIFIED_DIAMOND = ITEMS.register("purified_diamond", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> PURIFIED_EMERALD = ITEMS.register("purified_emerald", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> PURIFIED_ANCIENT_DEBRIS = ITEMS.register("purified_ancient_debris", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> ALCHEMICAL_ENGRAVER = ITEMS.register("alchemical_engraver",() -> new BlockItem(blocklist.ALCHEMICAL_ENGRAVER.get(), new Item.Properties()));
    public static final RegistryObject<Item> RUNE_ACTIVATOR = ITEMS.register("rune_activator",() -> new BlockItem(blocklist.RUNE_ACTIVATOR.get(), new Item.Properties()));
    public static final RegistryObject<Item> X9_COBBLESTONE = ITEMS.register("x9_cobblestone",() -> new BlockItem(blocklist.X9_COBBLESTONE.get(), new Item.Properties()));
    public static final RegistryObject<Item> X225_COBBLESTONE = ITEMS.register("x225_cobblestone",() -> new BlockItem(blocklist.X225_COBBLESTONE.get(), new Item.Properties()));
    public static final RegistryObject<Item> X38025_COBBLESTONE = ITEMS.register("x38025_cobblestone",() -> new BlockItem(blocklist.X38025_COBBLESTONE.get(), new Item.Properties()));
    public static final RegistryObject<Item> IMITATED_BEDROCK = ITEMS.register("imitated_bedrock",() -> new BlockItem(blocklist.IMITATED_BEDROCK.get(), new Item.Properties()));
    public static final RegistryObject<Item> PHILOSOPHERS_STONE = ITEMS.register("philosophers_stone", Philosophers_stone::new);
    public static final RegistryObject<Item> ARCANE_STAR = ITEMS.register("arcane_star", Arcane_Star::new);
    public static final RegistryObject<Item> ARCANE_DRAGON_EGG = ITEMS.register("arcane_dragon_egg", Arcane_Dragon_Egg::new);
    public static final RegistryObject<Item> SINGULARITY = ITEMS.register("singularity", Singularity::new);
    public static final RegistryObject<Item> T1_COMBUSTION_RUNE = ITEMS.register("t1_combustion_rune",() -> new FuelItem(new Item.Properties().rarity(Rarity.COMMON),2400));
    public static final RegistryObject<Item> T2_COMBUSTION_RUNE = ITEMS.register("t2_combustion_rune",() -> new FuelItem(new Item.Properties().rarity(Rarity.COMMON),3600));
    public static final RegistryObject<Item> T3_COMBUSTION_RUNE = ITEMS.register("t3_combustion_rune",() -> new FuelItem(new Item.Properties().rarity(Rarity.UNCOMMON),5400));
    public static final RegistryObject<Item> T4_COMBUSTION_RUNE = ITEMS.register("t4_combustion_rune",() -> new FuelItem(new Item.Properties().rarity(Rarity.UNCOMMON),8100));
    public static final RegistryObject<Item> T5_COMBUSTION_RUNE = ITEMS.register("t5_combustion_rune",() -> new FuelItem(new Item.Properties().rarity(Rarity.RARE),12150));
    public static final RegistryObject<Item> T6_COMBUSTION_RUNE = ITEMS.register("t6_combustion_rune",() -> new FuelItem(new Item.Properties().rarity(Rarity.RARE),18225));
    public static final RegistryObject<Item> SEMI_ETERNAL_FUEL = ITEMS.register("semi_eternal_fuel",Semi_Eternal_Fuel::new);
    public static final RegistryObject<Item> ETERNAL_FUEL = ITEMS.register("eternal_fuel", Eternal_Fuel::new);
    public static final RegistryObject<Item> T1_COMBUSTION_RUNE_BLOCK = ITEMS.register("t1_combustion_rune_block",() -> new BlockItem(blocklist.T1_COMBUSTION_RUNE_BLOCK.get(), new Item.Properties()));
    public static final RegistryObject<Item> T2_COMBUSTION_RUNE_BLOCK = ITEMS.register("t2_combustion_rune_block",() -> new BlockItem(blocklist.T2_COMBUSTION_RUNE_BLOCK.get(), new Item.Properties()));
    public static final RegistryObject<Item> T3_COMBUSTION_RUNE_BLOCK = ITEMS.register("t3_combustion_rune_block",() -> new BlockItem(blocklist.T3_COMBUSTION_RUNE_BLOCK.get(), new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> T4_COMBUSTION_RUNE_BLOCK = ITEMS.register("t4_combustion_rune_block",() -> new BlockItem(blocklist.T4_COMBUSTION_RUNE_BLOCK.get(), new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> T5_COMBUSTION_RUNE_BLOCK = ITEMS.register("t5_combustion_rune_block",() -> new BlockItem(blocklist.T5_COMBUSTION_RUNE_BLOCK.get(), new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> T6_COMBUSTION_RUNE_BLOCK = ITEMS.register("t6_combustion_rune_block",() -> new BlockItem(blocklist.T6_COMBUSTION_RUNE_BLOCK.get(), new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> T1_PANAKEIA_PICKAXE = ITEMS.register("t1_panakeia_pickaxe",() -> Panakeia_Pickaxes.T1_PANAKEIA_PICKAXE);
    public static final RegistryObject<Item> T2_PANAKEIA_PICKAXE = ITEMS.register("t2_panakeia_pickaxe",() -> Panakeia_Pickaxes.T2_PANAKEIA_PICKAXE);
    public static final RegistryObject<Item> T3_PANAKEIA_PICKAXE = ITEMS.register("t3_panakeia_pickaxe",() -> Panakeia_Pickaxes.T3_PANAKEIA_PICKAXE);
    public static final RegistryObject<Item> T4_PANAKEIA_PICKAXE = ITEMS.register("t4_panakeia_pickaxe",() -> Panakeia_Pickaxes.T4_PANAKEIA_PICKAXE);
    public static final RegistryObject<Item> T5_PANAKEIA_PICKAXE = ITEMS.register("t5_panakeia_pickaxe",() -> Panakeia_Pickaxes.T5_PANAKEIA_PICKAXE);
    public static final RegistryObject<Item> T6_PANAKEIA_PICKAXE = ITEMS.register("t6_panakeia_pickaxe",() -> Panakeia_Pickaxes.T6_PANAKEIA_PICKAXE);
    public static final RegistryObject<Item> UNITE_ALLOY_PICKAXE = ITEMS.register("unite_alloy_pickaxe",() -> Panakeia_Pickaxes.UNITE_ALLOY_PICKAXE);
    public static final RegistryObject<Item> T1_PANAKEIA_SHOVEL = ITEMS.register("t1_panakeia_shovel",() -> Panakeia_Shovels.T1_PANAKEIA_SHOVEL);
    public static final RegistryObject<Item> T2_PANAKEIA_SHOVEL = ITEMS.register("t2_panakeia_shovel",() -> Panakeia_Shovels.T2_PANAKEIA_SHOVEL);
    public static final RegistryObject<Item> T3_PANAKEIA_SHOVEL = ITEMS.register("t3_panakeia_shovel",() -> Panakeia_Shovels.T3_PANAKEIA_SHOVEL);
    public static final RegistryObject<Item> T4_PANAKEIA_SHOVEL = ITEMS.register("t4_panakeia_shovel",() -> Panakeia_Shovels.T4_PANAKEIA_SHOVEL);
    public static final RegistryObject<Item> T5_PANAKEIA_SHOVEL = ITEMS.register("t5_panakeia_shovel",() -> Panakeia_Shovels.T5_PANAKEIA_SHOVEL);
    public static final RegistryObject<Item> T6_PANAKEIA_SHOVEL = ITEMS.register("t6_panakeia_shovel",() -> Panakeia_Shovels.T6_PANAKEIA_SHOVEL);
    public static final RegistryObject<Item> UNITE_ALLOY_SHOVEL = ITEMS.register("unite_alloy_shovel",() -> Panakeia_Shovels.UNITE_ALLOY_SHOVEL);
    public static final RegistryObject<Item> T1_PANAKEIA_AXE = ITEMS.register("t1_panakeia_axe",() -> Panakeia_Axes.T1_PANAKEIA_AXE);
    public static final RegistryObject<Item> T2_PANAKEIA_AXE = ITEMS.register("t2_panakeia_axe",() -> Panakeia_Axes.T2_PANAKEIA_AXE);
    public static final RegistryObject<Item> T3_PANAKEIA_AXE = ITEMS.register("t3_panakeia_axe",() -> Panakeia_Axes.T3_PANAKEIA_AXE);
    public static final RegistryObject<Item> T4_PANAKEIA_AXE = ITEMS.register("t4_panakeia_axe",() -> Panakeia_Axes.T4_PANAKEIA_AXE);
    public static final RegistryObject<Item> T5_PANAKEIA_AXE = ITEMS.register("t5_panakeia_axe",() -> Panakeia_Axes.T5_PANAKEIA_AXE);
    public static final RegistryObject<Item> T6_PANAKEIA_AXE = ITEMS.register("t6_panakeia_axe",() -> Panakeia_Axes.T6_PANAKEIA_AXE);
    public static final RegistryObject<Item> UNITE_ALLOY_AXE = ITEMS.register("unite_alloy_axe",() -> Panakeia_Axes.UNITE_ALLOY_AXE);
    public static final RegistryObject<Item> T1_PANAKEIA_HOE = ITEMS.register("t1_panakeia_hoe",() -> Panakeia_Hoes.T1_PANAKEIA_HOE);
    public static final RegistryObject<Item> T2_PANAKEIA_HOE = ITEMS.register("t2_panakeia_hoe",() -> Panakeia_Hoes.T2_PANAKEIA_HOE);
    public static final RegistryObject<Item> T3_PANAKEIA_HOE = ITEMS.register("t3_panakeia_hoe",() -> Panakeia_Hoes.T3_PANAKEIA_HOE);
    public static final RegistryObject<Item> T4_PANAKEIA_HOE = ITEMS.register("t4_panakeia_hoe",() -> Panakeia_Hoes.T4_PANAKEIA_HOE);
    public static final RegistryObject<Item> T5_PANAKEIA_HOE = ITEMS.register("t5_panakeia_hoe",() -> Panakeia_Hoes.T5_PANAKEIA_HOE);
    public static final RegistryObject<Item> T6_PANAKEIA_HOE = ITEMS.register("t6_panakeia_hoe",() -> Panakeia_Hoes.T6_PANAKEIA_HOE);
    public static final RegistryObject<Item> UNITE_ALLOY_HOE = ITEMS.register("unite_alloy_hoe",() -> Panakeia_Hoes.UNITE_ALLOY_HOE);
    public static final RegistryObject<Item> T1_PANAKEIA_SWORD = ITEMS.register("t1_panakeia_sword",() -> Panakeia_Swords.T1_PANAKEIA_SWORD);
    public static final RegistryObject<Item> T2_PANAKEIA_SWORD = ITEMS.register("t2_panakeia_sword",() -> Panakeia_Swords.T2_PANAKEIA_SWORD);
    public static final RegistryObject<Item> T3_PANAKEIA_SWORD = ITEMS.register("t3_panakeia_sword",() -> Panakeia_Swords.T3_PANAKEIA_SWORD);
    public static final RegistryObject<Item> T4_PANAKEIA_SWORD = ITEMS.register("t4_panakeia_sword",() -> Panakeia_Swords.T4_PANAKEIA_SWORD);
    public static final RegistryObject<Item> T5_PANAKEIA_SWORD = ITEMS.register("t5_panakeia_sword",() -> Panakeia_Swords.T5_PANAKEIA_SWORD);
    public static final RegistryObject<Item> T6_PANAKEIA_SWORD = ITEMS.register("t6_panakeia_sword",() -> Panakeia_Swords.T6_PANAKEIA_SWORD);
    public static final RegistryObject<Item> UNITE_ALLOY_SWORD = ITEMS.register("unite_alloy_sword",() -> Panakeia_Swords.UNITE_ALLOY_SWORD);
    public static final RegistryObject<Item> T1_PANAKEIA_CUBE = ITEMS.register("t1_panakeia_cube",CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> T2_PANAKEIA_CUBE = ITEMS.register("t2_panakeia_cube",CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> T3_PANAKEIA_CUBE = ITEMS.register("t3_panakeia_cube",CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> T4_PANAKEIA_CUBE = ITEMS.register("t4_panakeia_cube",UncommonAlchemyMaterial::new);
    public static final RegistryObject<Item> T5_PANAKEIA_CUBE = ITEMS.register("t5_panakeia_cube",UncommonAlchemyMaterial::new);
    public static final RegistryObject<Item> T6_PANAKEIA_CUBE = ITEMS.register("t6_panakeia_cube",RareAlchemyMaterial::new);
    public static final RegistryObject<Item> T7_PANAKEIA_CUBE = ITEMS.register("t7_panakeia_cube",EpicAlchemyMaterial::new);
    public static final RegistryObject<Item> T1_PANAKEIA_HELMET = ITEMS.register("t1_panakeia_helmet",() -> Panakeia_Armors.T1_PANAKEIA_HELMET);
    public static final RegistryObject<Item> T1_PANAKEIA_CHESTPLATE = ITEMS.register("t1_panakeia_chestplate",() -> Panakeia_Armors.T1_PANAKEIA_CHESTPLATE);
    public static final RegistryObject<Item> T1_PANAKEIA_LEGGINGS = ITEMS.register("t1_panakeia_leggings",() -> Panakeia_Armors.T1_PANAKEIA_LEGGINGS);
    public static final RegistryObject<Item> T1_PANAKEIA_BOOTS = ITEMS.register("t1_panakeia_boots",() -> Panakeia_Armors.T1_PANAKEIA_BOOTS);
    public static final RegistryObject<Item> T2_PANAKEIA_HELMET = ITEMS.register("t2_panakeia_helmet",() -> Panakeia_Armors.T2_PANAKEIA_HELMET);
    public static final RegistryObject<Item> T2_PANAKEIA_CHESTPLATE = ITEMS.register("t2_panakeia_chestplate",() -> Panakeia_Armors.T2_PANAKEIA_CHESTPLATE);
    public static final RegistryObject<Item> T2_PANAKEIA_LEGGINGS = ITEMS.register("t2_panakeia_leggings",() -> Panakeia_Armors.T2_PANAKEIA_LEGGINGS);
    public static final RegistryObject<Item> T2_PANAKEIA_BOOTS = ITEMS.register("t2_panakeia_boots",() -> Panakeia_Armors.T2_PANAKEIA_BOOTS);
    public static final RegistryObject<Item> T3_PANAKEIA_HELMET = ITEMS.register("t3_panakeia_helmet",() -> Panakeia_Armors.T3_PANAKEIA_HELMET);
    public static final RegistryObject<Item> T3_PANAKEIA_CHESTPLATE = ITEMS.register("t3_panakeia_chestplate",() -> Panakeia_Armors.T3_PANAKEIA_CHESTPLATE);
    public static final RegistryObject<Item> T3_PANAKEIA_LEGGINGS = ITEMS.register("t3_panakeia_leggings",() -> Panakeia_Armors.T3_PANAKEIA_LEGGINGS);
    public static final RegistryObject<Item> T3_PANAKEIA_BOOTS = ITEMS.register("t3_panakeia_boots",() -> Panakeia_Armors.T3_PANAKEIA_BOOTS);
    public static final RegistryObject<Item> T4_PANAKEIA_HELMET = ITEMS.register("t4_panakeia_helmet",() -> Panakeia_Armors.T4_PANAKEIA_HELMET);
    public static final RegistryObject<Item> T4_PANAKEIA_CHESTPLATE = ITEMS.register("t4_panakeia_chestplate",() -> Panakeia_Armors.T4_PANAKEIA_CHESTPLATE);
    public static final RegistryObject<Item> T4_PANAKEIA_LEGGINGS = ITEMS.register("t4_panakeia_leggings",() -> Panakeia_Armors.T4_PANAKEIA_LEGGINGS);
    public static final RegistryObject<Item> T4_PANAKEIA_BOOTS = ITEMS.register("t4_panakeia_boots",() -> Panakeia_Armors.T4_PANAKEIA_BOOTS);
    public static final RegistryObject<Item> T5_PANAKEIA_HELMET = ITEMS.register("t5_panakeia_helmet",() -> Panakeia_Armors.T5_PANAKEIA_HELMET);
    public static final RegistryObject<Item> T5_PANAKEIA_CHESTPLATE = ITEMS.register("t5_panakeia_chestplate",() -> Panakeia_Armors.T5_PANAKEIA_CHESTPLATE);
    public static final RegistryObject<Item> T5_PANAKEIA_LEGGINGS = ITEMS.register("t5_panakeia_leggings",() -> Panakeia_Armors.T5_PANAKEIA_LEGGINGS);
    public static final RegistryObject<Item> T5_PANAKEIA_BOOTS = ITEMS.register("t5_panakeia_boots",() -> Panakeia_Armors.T5_PANAKEIA_BOOTS);
    public static final RegistryObject<Item> T6_PANAKEIA_HELMET = ITEMS.register("t6_panakeia_helmet",() -> Panakeia_Armors.T6_PANAKEIA_HELMET);
    public static final RegistryObject<Item> T6_PANAKEIA_CHESTPLATE = ITEMS.register("t6_panakeia_chestplate",() -> Panakeia_Armors.T6_PANAKEIA_CHESTPLATE);
    public static final RegistryObject<Item> T6_PANAKEIA_LEGGINGS = ITEMS.register("t6_panakeia_leggings",() -> Panakeia_Armors.T6_PANAKEIA_LEGGINGS);
    public static final RegistryObject<Item> T6_PANAKEIA_BOOTS = ITEMS.register("t6_panakeia_boots",() -> Panakeia_Armors.T6_PANAKEIA_BOOTS);
    public static final RegistryObject<Item> UNITE_ALLOY_HELMET = ITEMS.register("unite_alloy_helmet",() -> Panakeia_Armors.UNITE_ALLOY_HELMET);
    public static final RegistryObject<Item> UNITE_ALLOY_CHESTPLATE = ITEMS.register("unite_alloy_chestplate",() -> Panakeia_Armors.UNITE_ALLOY_CHESTPLATE);
    public static final RegistryObject<Item> UNITE_ALLOY_LEGGINGS = ITEMS.register("unite_alloy_leggings",() -> Panakeia_Armors.UNITE_ALLOY_LEGGINGS);
    public static final RegistryObject<Item> UNITE_ALLOY_BOOTS = ITEMS.register("unite_alloy_boots",() -> Panakeia_Armors.UNITE_ALLOY_BOOTS);
    public static final RegistryObject<Item> THE_DESTROYER_OF_THE_RIAL = ITEMS.register("the_destroyer_of_the_rial",The_Destroyer_of_the_Rial::new);
    public static final RegistryObject<Item> ANGEL_RING = ITEMS.register("angel_ring",Angel_Ring::new);
    public static final RegistryObject<Item> CRIMSON_PLATE_OF_JUSTICE = ITEMS.register("crimson_plate_of_justice",Crimson_Plate_of_Justice::new);
    public static final RegistryObject<Item> LEGGINGS_OF_SAGA = ITEMS.register("leggings_of_saga", Leggings_of_Sage::new);
    public static final RegistryObject<Item> MARCH_OF_THE_RULER = ITEMS.register("march_of_the_ruler", March_of_the_Ruler::new);
    public static final RegistryObject<Item> BLADE_OF_VALOR = ITEMS.register("blade_of_valor",BladeOfValor::new);
    public static final RegistryObject<Item> SINGULARITY_NUGGET = ITEMS.register("singularity_nugget",EpicAlchemyMaterial::new);
    public static final RegistryObject<Item> SINGULARITY_INGOT = ITEMS.register("singularity_ingot",EpicAlchemyMaterial::new);
    public static final RegistryObject<Item> UNITE_ALLOY_SMITHING_TEMPLATE = ITEMS.register("unite_alloy_smithing_template",Unite_Alloy_Smithing_Template::new);
    public static final RegistryObject<Item> SINGULARITY_INGOT_SMITHING_TEMPLATE = ITEMS.register("singularity_ingot_smithing_template",Singularity_Ingot_Smithing_Template::new);

    public static final RegistryObject<Item> CROWN_OF_THE_SERAPH = ITEMS.register("crown_of_the_seraph",CrownOfTheSeraph::new);
    public static final RegistryObject<Item> JUDICIAL_CARAPACE = ITEMS.register("judicial_carapace",JudicialCarapace::new);
    public static final RegistryObject<Item> GAIT_OF_INSIGHT = ITEMS.register("gait_of_insight",GaitOfInsight::new);
    public static final RegistryObject<Item> BOOTS_OF_AETHERLIGHT = ITEMS.register("boots_of_aetherlight",BootsOfAetherlight::new);
    public static final RegistryObject<Item> SEVEN_SWORDS_OF_TERMINUS = ITEMS.register("seven_swords_of_terminus",SevenSwordsOfTerminus::new);
    public static final RegistryObject<Item> RUNE_OF_REPRODUCTION = ITEMS.register("rune_of_reproduction",Rune_of_Reproduction::new);

    public static final RegistryObject<Item> FOUNDATION_OF_RING = ITEMS.register("foundation_of_ring", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> ALCHEMISTS_RING = ITEMS.register("alchemists_ring", Alchemists_ring::new);
    public static final RegistryObject<Item> GLUTTONYS_RING = ITEMS.register("gluttonys_ring", Gluttonys_ring::new);
    public static final RegistryObject<Item> GREED_RING = ITEMS.register("greed_ring", Greed_Ring::new);
    public static final RegistryObject<Item> RUNE_OF_EQUIVALENT = ITEMS.register("rune_of_equivalent", Rune_of_Equivalent::new);


    public static final RegistryObject<Item> RUNE_OF_FRUITS = ITEMS.register("rune_of_fruits",Rune_of_Fruits::new);
    public static final RegistryObject<Item> COOKWARE_SET = ITEMS.register("cookware_set",Cookware_Set::new);
    public static final RegistryObject<Item> COLLECTED_CRUSHED_RAW_COPPER = ITEMS.register("collected_crushed_raw_copper", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> COLLECTED_CRUSHED_RAW_IRON = ITEMS.register("collected_crushed_raw_iron", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> COLLECTED_CRUSHED_RAW_GOLD = ITEMS.register("collected_crushed_raw_gold", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> COLLECTED_CRUSHED_DIAMOND_ORE = ITEMS.register("collected_crushed_diamond_ore", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> COLLECTED_CRUSHED_EMERALD_ORE = ITEMS.register("collected_crushed_emerald_ore", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> COLLECTED_CRUSHED_ANCIENT_DEBRIS = ITEMS.register("collected_crushed_ancient_debris", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> COLLECTED_GRANULATED_COPPER = ITEMS.register("collected_granulated_copper", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> COLLECTED_GRANULATED_IRON = ITEMS.register("collected_granulated_iron", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> COLLECTED_GRANULATED_GOLD = ITEMS.register("collected_granulated_gold", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> COLLECTED_GRANULATED_DIAMOND = ITEMS.register("collected_granulated_diamond", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> COLLECTED_GRANULATED_EMERALD = ITEMS.register("collected_granulated_emerald", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> COLLECTED_GRANULATED_ANCIENT_DEBRIS = ITEMS.register("collected_granulated_ancient_debris", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> COLLECTED_SOFTENED_COPPER = ITEMS.register("collected_softened_copper", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> COLLECTED_SOFTENED_IRON = ITEMS.register("collected_softened_iron", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> COLLECTED_SOFTENED_GOLD = ITEMS.register("collected_softened_gold", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> COLLECTED_SOFTENED_DIAMOND = ITEMS.register("collected_softened_diamond", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> COLLECTED_SOFTENED_EMERALD = ITEMS.register("collected_softened_emerald", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> COLLECTED_SOFTENED_ANCIENT_DEBRIS = ITEMS.register("collected_softened_ancient_debris", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> COLLECTED_PURIFIED_COPPER = ITEMS.register("collected_purified_copper", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> COLLECTED_PURIFIED_IRON = ITEMS.register("collected_purified_iron", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> COLLECTED_PURIFIED_GOLD = ITEMS.register("collected_purified_gold", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> COLLECTED_PURIFIED_DIAMOND = ITEMS.register("collected_purified_diamond", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> COLLECTED_PURIFIED_EMERALD = ITEMS.register("collected_purified_emerald", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> COLLECTED_PURIFIED_ANCIENT_DEBRIS = ITEMS.register("collected_purified_ancient_debris", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> PACKAGED_CRUSHED_RAW_COPPER = ITEMS.register("packaged_crushed_raw_copper", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> PACKAGED_CRUSHED_RAW_IRON = ITEMS.register("packaged_crushed_raw_iron", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> PACKAGED_CRUSHED_RAW_GOLD = ITEMS.register("packaged_crushed_raw_gold", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> PACKAGED_CRUSHED_DIAMOND_ORE = ITEMS.register("packaged_crushed_diamond_ore", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> PACKAGED_CRUSHED_EMERALD_ORE = ITEMS.register("packaged_crushed_emerald_ore", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> PACKAGED_CRUSHED_ANCIENT_DEBRIS = ITEMS.register("packaged_crushed_ancient_debris", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> PACKAGED_GRANULATED_COPPER = ITEMS.register("packaged_granulated_copper", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> PACKAGED_GRANULATED_IRON = ITEMS.register("packaged_granulated_iron", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> PACKAGED_GRANULATED_GOLD = ITEMS.register("packaged_granulated_gold", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> PACKAGED_GRANULATED_DIAMOND = ITEMS.register("packaged_granulated_diamond", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> PACKAGED_GRANULATED_EMERALD = ITEMS.register("packaged_granulated_emerald", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> PACKAGED_GRANULATED_ANCIENT_DEBRIS = ITEMS.register("packaged_granulated_ancient_debris", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> PACKAGED_SOFTENED_COPPER = ITEMS.register("packaged_softened_copper", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> PACKAGED_SOFTENED_IRON = ITEMS.register("packaged_softened_iron", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> PACKAGED_SOFTENED_GOLD = ITEMS.register("packaged_softened_gold", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> PACKAGED_SOFTENED_DIAMOND = ITEMS.register("packaged_softened_diamond", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> PACKAGED_SOFTENED_EMERALD = ITEMS.register("packaged_softened_emerald", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> PACKAGED_SOFTENED_ANCIENT_DEBRIS = ITEMS.register("packaged_softened_ancient_debris", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> PACKAGED_PURIFIED_COPPER = ITEMS.register("packaged_purified_copper", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> PACKAGED_PURIFIED_IRON = ITEMS.register("packaged_purified_iron", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> PACKAGED_PURIFIED_GOLD = ITEMS.register("packaged_purified_gold", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> PACKAGED_PURIFIED_DIAMOND = ITEMS.register("packaged_purified_diamond", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> PACKAGED_PURIFIED_EMERALD = ITEMS.register("packaged_purified_emerald", CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> PACKAGED_PURIFIED_ANCIENT_DEBRIS = ITEMS.register("packaged_purified_ancient_debris", CommonAlchemyMaterial::new);

    public static final RegistryObject<Item> COBBLESTONE_GENERATOR_Mk1 = ITEMS.register("cobblestone_generator_mk1", () -> new BlockItem(blocklist.COBBLESTONE_GENERATOR_MK1.get(), new Item.Properties()));
    public static final RegistryObject<Item> COBBLESTONE_GENERATOR_Mk2 = ITEMS.register("cobblestone_generator_mk2", () -> new BlockItem(blocklist.COBBLESTONE_GENERATOR_MK2.get(), new Item.Properties()));
    public static final RegistryObject<Item> COBBLESTONE_GENERATOR_Mk3 = ITEMS.register("cobblestone_generator_mk3", () -> new BlockItem(blocklist.COBBLESTONE_GENERATOR_MK3.get(), new Item.Properties()));
    public static final RegistryObject<Item> COBBLESTONE_GENERATOR_Mk4 = ITEMS.register("cobblestone_generator_mk4", () -> new BlockItem(blocklist.COBBLESTONE_GENERATOR_MK4.get(), new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> COBBLESTONE_GENERATOR_Mk5 = ITEMS.register("cobblestone_generator_mk5", () -> new BlockItem(blocklist.COBBLESTONE_GENERATOR_MK5.get(), new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> COBBLESTONE_GENERATOR_Mk6 = ITEMS.register("cobblestone_generator_mk6", () -> new BlockItem(blocklist.COBBLESTONE_GENERATOR_MK6.get(), new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> COBBLESTONE_GENERATOR_Mk7 = ITEMS.register("cobblestone_generator_mk7", () -> new BlockItem(blocklist.COBBLESTONE_GENERATOR_MK7.get(), new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> COBBLESTONE_GENERATOR_Mk8 = ITEMS.register("cobblestone_generator_mk8", () -> new BlockItem(blocklist.COBBLESTONE_GENERATOR_MK8.get(), new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> X9_COBBLESTONE_GENERATOR_Mk1 = ITEMS.register("x9_cobblestone_generator_mk1", () -> new BlockItem(blocklist.X9_COBBLESTONE_GENERATOR_MK1.get(), new Item.Properties()));
    public static final RegistryObject<Item> X9_COBBLESTONE_GENERATOR_Mk2 = ITEMS.register("x9_cobblestone_generator_mk2", () -> new BlockItem(blocklist.X9_COBBLESTONE_GENERATOR_MK2.get(), new Item.Properties()));
    public static final RegistryObject<Item> X9_COBBLESTONE_GENERATOR_Mk3 = ITEMS.register("x9_cobblestone_generator_mk3", () -> new BlockItem(blocklist.X9_COBBLESTONE_GENERATOR_MK3.get(), new Item.Properties()));
    public static final RegistryObject<Item> X9_COBBLESTONE_GENERATOR_Mk4 = ITEMS.register("x9_cobblestone_generator_mk4", () -> new BlockItem(blocklist.X9_COBBLESTONE_GENERATOR_MK4.get(), new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> X9_COBBLESTONE_GENERATOR_Mk5 = ITEMS.register("x9_cobblestone_generator_mk5", () -> new BlockItem(blocklist.X9_COBBLESTONE_GENERATOR_MK5.get(), new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> X9_COBBLESTONE_GENERATOR_Mk6 = ITEMS.register("x9_cobblestone_generator_mk6", () -> new BlockItem(blocklist.X9_COBBLESTONE_GENERATOR_MK6.get(), new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> X9_COBBLESTONE_GENERATOR_Mk7 = ITEMS.register("x9_cobblestone_generator_mk7", () -> new BlockItem(blocklist.X9_COBBLESTONE_GENERATOR_MK7.get(), new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> X9_COBBLESTONE_GENERATOR_Mk8 = ITEMS.register("x9_cobblestone_generator_mk8", () -> new BlockItem(blocklist.X9_COBBLESTONE_GENERATOR_MK8.get(), new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> X225_COBBLESTONE_GENERATOR_Mk1 = ITEMS.register("x225_cobblestone_generator_mk1", () -> new BlockItem(blocklist.X225_COBBLESTONE_GENERATOR_MK1.get(), new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> X225_COBBLESTONE_GENERATOR_Mk2 = ITEMS.register("x225_cobblestone_generator_mk2", () -> new BlockItem(blocklist.X225_COBBLESTONE_GENERATOR_MK2.get(), new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> X225_COBBLESTONE_GENERATOR_Mk3 = ITEMS.register("x225_cobblestone_generator_mk3", () -> new BlockItem(blocklist.X225_COBBLESTONE_GENERATOR_MK3.get(), new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> X225_COBBLESTONE_GENERATOR_Mk4 = ITEMS.register("x225_cobblestone_generator_mk4", () -> new BlockItem(blocklist.X225_COBBLESTONE_GENERATOR_MK4.get(), new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> X225_COBBLESTONE_GENERATOR_Mk5 = ITEMS.register("x225_cobblestone_generator_mk5", () -> new BlockItem(blocklist.X225_COBBLESTONE_GENERATOR_MK5.get(), new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> X225_COBBLESTONE_GENERATOR_Mk6 = ITEMS.register("x225_cobblestone_generator_mk6", () -> new BlockItem(blocklist.X225_COBBLESTONE_GENERATOR_MK6.get(), new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> X225_COBBLESTONE_GENERATOR_Mk7 = ITEMS.register("x225_cobblestone_generator_mk7", () -> new BlockItem(blocklist.X225_COBBLESTONE_GENERATOR_MK7.get(), new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> X225_COBBLESTONE_GENERATOR_Mk8 = ITEMS.register("x225_cobblestone_generator_mk8", () -> new BlockItem(blocklist.X225_COBBLESTONE_GENERATOR_MK8.get(), new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> X38025_COBBLESTONE_GENERATOR_Mk1 = ITEMS.register("x38025_cobblestone_generator_mk1", () -> new BlockItem(blocklist.X38025_COBBLESTONE_GENERATOR_MK1.get(), new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> X38025_COBBLESTONE_GENERATOR_Mk2 = ITEMS.register("x38025_cobblestone_generator_mk2", () -> new BlockItem(blocklist.X38025_COBBLESTONE_GENERATOR_MK2.get(), new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> X38025_COBBLESTONE_GENERATOR_Mk3 = ITEMS.register("x38025_cobblestone_generator_mk3", () -> new BlockItem(blocklist.X38025_COBBLESTONE_GENERATOR_MK3.get(), new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> X38025_COBBLESTONE_GENERATOR_Mk4 = ITEMS.register("x38025_cobblestone_generator_mk4", () -> new BlockItem(blocklist.X38025_COBBLESTONE_GENERATOR_MK4.get(), new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> X38025_COBBLESTONE_GENERATOR_Mk5 = ITEMS.register("x38025_cobblestone_generator_mk5", () -> new BlockItem(blocklist.X38025_COBBLESTONE_GENERATOR_MK5.get(), new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> X38025_COBBLESTONE_GENERATOR_Mk6 = ITEMS.register("x38025_cobblestone_generator_mk6", () -> new BlockItem(blocklist.X38025_COBBLESTONE_GENERATOR_MK6.get(), new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> X38025_COBBLESTONE_GENERATOR_Mk7 = ITEMS.register("x38025_cobblestone_generator_mk7", () -> new BlockItem(blocklist.X38025_COBBLESTONE_GENERATOR_MK7.get(), new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> X38025_COBBLESTONE_GENERATOR_Mk8 = ITEMS.register("x38025_cobblestone_generator_mk8", () -> new BlockItem(blocklist.X38025_COBBLESTONE_GENERATOR_MK8.get(), new Item.Properties().rarity(Rarity.EPIC)));

    public static final RegistryObject<Item> ALCHETREE_LOG = ITEMS.register("alchetree_log", () -> new BlockItem(blocklist.ALCHETREE_LOG.get(), new Item.Properties()));
    public static final RegistryObject<Item> ALCHETREE_WOOD = ITEMS.register("alchetree_wood", () -> new BlockItem(blocklist.ALCHETREE_WOOD.get(), new Item.Properties()));
    public static final RegistryObject<Item> STRIPPED_ALCHETREE_LOG = ITEMS.register("stripped_alchetree_log", () -> new BlockItem(blocklist.STRIPPED_ALCHETREE_LOG.get(), new Item.Properties()));
    public static final RegistryObject<Item> STRIPPED_ALCHETREE_WOOD = ITEMS.register("stripped_alchetree_wood", () -> new BlockItem(blocklist.STRIPPED_ALCHETREE_WOOD.get(), new Item.Properties()));
    public static final RegistryObject<Item> ALCHETREE_PLANKS = ITEMS.register("alchetree_planks", () -> new BlockItem(blocklist.ALCHETREE_PLANKS.get(), new Item.Properties()));
    public static final RegistryObject<Item> ALCHETREE_SAPLINGS_T0 = ITEMS.register("alchetree_sapling_t0",() -> new BlockItem(blocklist.ALCHETREE_SAPLINGS_T0.get(),new Item.Properties()));
    public static final RegistryObject<Item> ALCHETREE_SAPLINGS_T1 = ITEMS.register("alchetree_sapling_t1",() -> new BlockItem(blocklist.ALCHETREE_SAPLINGS_T1.get(),new Item.Properties()));
    public static final RegistryObject<Item> ALCHETREE_SAPLINGS_T2 = ITEMS.register("alchetree_sapling_t2",() -> new BlockItem(blocklist.ALCHETREE_SAPLINGS_T2.get(),new Item.Properties()));
    public static final RegistryObject<Item> ALCHETREE_SAPLINGS_T3 = ITEMS.register("alchetree_sapling_t3",() -> new BlockItem(blocklist.ALCHETREE_SAPLINGS_T3.get(),new Item.Properties()));
    public static final RegistryObject<Item> ALCHETREE_SAPLINGS_T4 = ITEMS.register("alchetree_sapling_t4",() -> new BlockItem(blocklist.ALCHETREE_SAPLINGS_T4.get(),new Item.Properties()));
    public static final RegistryObject<Item> ALCHETREE_SAPLINGS_T5 = ITEMS.register("alchetree_sapling_t5",() -> new BlockItem(blocklist.ALCHETREE_SAPLINGS_T5.get(),new Item.Properties()));
    public static final RegistryObject<Item> ALCHETREE_SAPLINGS_T6 = ITEMS.register("alchetree_sapling_t6",() -> new BlockItem(blocklist.ALCHETREE_SAPLINGS_T6.get(),new Item.Properties()));
    public static final RegistryObject<Item> ALCHETREE_SAPLINGS_T7 = ITEMS.register("alchetree_sapling_t7",() -> new BlockItem(blocklist.ALCHETREE_SAPLINGS_T7.get(),new Item.Properties()));
    public static final RegistryObject<Item>[] ALCHETREE_LEAVES = new RegistryObject[8];
    static {
        for (int tier = 0; tier <8 ; tier++){
            int finalTier = tier;
            ALCHETREE_LEAVES[tier] = ITEMS.register("alchetree_leaves_t"+tier,() -> new BlockItem(blocklist.ALCHETREE_LEAVES[finalTier].get(),new Item.Properties()));
        }
    }
    public static final RegistryObject<Item> ALCHETREE_STAIRS = ITEMS.register("alchetree_stairs", () -> new BlockItem(blocklist.ALCHETREE_STAIRS.get(), new Item.Properties()));
    public static final RegistryObject<Item> ALCHETREE_SLAB = ITEMS.register("alchetree_slab", () -> new BlockItem(blocklist.ALCHETREE_SLAB.get(), new Item.Properties()));
    public static final RegistryObject<Item> ALCHETREE_FENCE = ITEMS.register("alchetree_fence", () -> new BlockItem(blocklist.ALCHETREE_FENCE.get(), new Item.Properties()));
    public static final RegistryObject<Item> ALCHETREE_FENCE_GATE = ITEMS.register("alchetree_fence_gate", () -> new BlockItem(blocklist.ALCHETREE_FENCE_GATE.get(), new Item.Properties()));
    public static final RegistryObject<Item> ALCHETREE_WALL = ITEMS.register("alchetree_wall", () -> new BlockItem(blocklist.ALCHETREE_WALL.get(), new Item.Properties()));
    public static final RegistryObject<Item> ALCHETREE_PRESSURE_PLATE = ITEMS.register("alchetree_pressure_plate", () -> new BlockItem(blocklist.ALCHETREE_PRESSURE_PLATE.get(), new Item.Properties()));
    public static final RegistryObject<Item> ALCHETREE_BUTTON = ITEMS.register("alchetree_button", () -> new BlockItem(blocklist.ALCHETREE_BUTTON.get(), new Item.Properties()));
    public static final RegistryObject<Item> ALCHETREE_TRAPDOOR = ITEMS.register("alchetree_trapdoor", () -> new BlockItem(blocklist.ALCHETREE_TRAPDOOR.get(), new Item.Properties()));
    public static final RegistryObject<Item> ALCHETREE_DOOR = ITEMS.register("alchetree_door", () -> new BlockItem(blocklist.ALCHETREE_DOOR.get(), new Item.Properties()));


    public static final RegistryObject<Item> T1_PANAKEIA_INGOT_X81_COMPRESSED_PLATE = ITEMS.register("t1_panakeia_ingot_x81_compressed_plate",CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> T2_PANAKEIA_INGOT_X81_COMPRESSED_PLATE = ITEMS.register("t2_panakeia_ingot_x81_compressed_plate",CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> T3_PANAKEIA_INGOT_X81_COMPRESSED_PLATE = ITEMS.register("t3_panakeia_ingot_x81_compressed_plate",CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> T4_PANAKEIA_GEM_X81_COMPRESSED_PLATE = ITEMS.register("t4_panakeia_gem_x81_compressed_plate",UncommonAlchemyMaterial::new);
    public static final RegistryObject<Item> T5_PANAKEIA_GEM_X81_COMPRESSED_PLATE = ITEMS.register("t5_panakeia_gem_x81_compressed_plate",UncommonAlchemyMaterial::new);
    public static final RegistryObject<Item> T6_PANAKEIA_INGOT_X81_COMPRESSED_PLATE = ITEMS.register("t6_panakeia_ingot_x81_compressed_plate",RareAlchemyMaterial::new);
    public static final RegistryObject<Item> UNITE_ALLOY_X81_COMPRESSED_PLATE = ITEMS.register("unite_alloy_x81_compressed_plate",EpicAlchemyMaterial::new);
    public static final RegistryObject<Item> T1_PANAKEIA_INGOT_X2025_COMPRESSED_PLATE = ITEMS.register("t1_panakeia_ingot_x2025_compressed_plate",CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> T2_PANAKEIA_INGOT_X2025_COMPRESSED_PLATE = ITEMS.register("t2_panakeia_ingot_x2025_compressed_plate",CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> T3_PANAKEIA_INGOT_X2025_COMPRESSED_PLATE = ITEMS.register("t3_panakeia_ingot_x2025_compressed_plate",CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> T4_PANAKEIA_GEM_X2025_COMPRESSED_PLATE = ITEMS.register("t4_panakeia_gem_x2025_compressed_plate",UncommonAlchemyMaterial::new);
    public static final RegistryObject<Item> T5_PANAKEIA_GEM_X2025_COMPRESSED_PLATE = ITEMS.register("t5_panakeia_gem_x2025_compressed_plate",UncommonAlchemyMaterial::new);
    public static final RegistryObject<Item> T6_PANAKEIA_INGOT_X2025_COMPRESSED_PLATE = ITEMS.register("t6_panakeia_ingot_x2025_compressed_plate",RareAlchemyMaterial::new);
    public static final RegistryObject<Item> UNITE_ALLOY_X2025_COMPRESSED_PLATE = ITEMS.register("unite_alloy_x2025_compressed_plate",EpicAlchemyMaterial::new);
    public static final RegistryObject<Item> WISDOM_CRYSTAL_PLATE = ITEMS.register("wisdom_crystal_plate",EpicAlchemyMaterial::new);
    public static final RegistryObject<Item> COURAGE_CRYSTAL_PLATE = ITEMS.register("courage_crystal_plate",EpicAlchemyMaterial::new);
    public static final RegistryObject<Item> JUSTICE_CRYSTAL_PLATE = ITEMS.register("justice_crystal_plate",EpicAlchemyMaterial::new);
    public static final RegistryObject<Item> LOVE_CRYSTAL_PLATE = ITEMS.register("love_crystal_plate",EpicAlchemyMaterial::new);
    public static final RegistryObject<Item> HOPE_CRYSTAL_PLATE = ITEMS.register("hope_crystal_plate",EpicAlchemyMaterial::new);
    public static final RegistryObject<Item> TEMPERANCE_CRYSTAL_PLATE = ITEMS.register("temperance_crystal_plate",EpicAlchemyMaterial::new);
    public static final RegistryObject<Item> FAITH_CRYSTAL_PLATE = ITEMS.register("faith_crystal_plate",EpicAlchemyMaterial::new);

    public static final RegistryObject<Item> ALCHETREE_MYSTERIOUS_SCARECROW = ITEMS.register("alchetree_mysterious_scarecrow",MysteriousScarecrowItem::new);
    public static final RegistryObject<Item> INFINITE_WATER_BARREL = ITEMS.register("infinite_water_barrel", () -> new BlockItem(blocklist.INFINITE_WATER_BARREL.get(), new Item.Properties()));
    public static final RegistryObject<Item> INFINITE_LAVA_BARREL = ITEMS.register("infinite_lava_barrel", () -> new BlockItem(blocklist.INFINITE_LAVA_BARREL.get(), new Item.Properties()));


    //食材系アイテム（材料系）
    public static final RegistryObject<Item> TOMATO = ITEMS.register("tomato",() -> new BaseFoodItem(64,2,0.6F));
    public static final RegistryObject<Item> CABBAGE = ITEMS.register("cabbage",() -> new BaseFoodItem(64,2,0.6F));
    public static final RegistryObject<Item> ONION = ITEMS.register("onion",() -> new BaseFoodItem(64,2,0.6F));
    public static final RegistryObject<Item> CHEESE = ITEMS.register("cheese",() -> new BaseFoodItem(64,2,0.6F));
    public static final RegistryObject<Item> RAW_PASTA = ITEMS.register("raw_pasta",() -> new BaseFoodItem(64,2,0.6F));
    public static final RegistryObject<Item> DOUGH = ITEMS.register("dough",() -> new BaseFoodItem(64,2,0.6F));
    public static final RegistryObject<Item> FLOUR = ITEMS.register("flour",CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> RICE = ITEMS.register("rice",() -> new BaseFoodItem(64,2,0.6F));
    public static final RegistryObject<Item> SLICED_APPLE = ITEMS.register("sliced_apple",() -> new BaseFoodItem(64,2,0.6F));
    public static final RegistryObject<Item> CHOPPED_SEAWEED = ITEMS.register("chopped_seaweed",() -> new BaseFoodItem(64,2,0.6F));
    public static final RegistryObject<Item> NORI = ITEMS.register("nori",() -> new BaseFoodItem(64,2,0.6F));
    public static final RegistryObject<Item> CHOCOLATE = ITEMS.register("chocolate",() -> new BaseFoodItem(64,2,0.6F));
    public static final RegistryObject<Item> LEMON = ITEMS.register("lemon",() -> new BaseFoodItem(64,2,0.6F));
    public static final RegistryObject<Item> SALT = ITEMS.register("salt",CommonAlchemyMaterial::new );
    public static final RegistryObject<Item> VINEGAR = ITEMS.register("vinegar",CommonAlchemyMaterial::new );
    public static final RegistryObject<Item> COOKING_OIL = ITEMS.register("cooking_oil",CommonAlchemyMaterial::new );
    public static final RegistryObject<Item> BUTTER = ITEMS.register("butter",CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> COD_ROE = ITEMS.register("cod_roe",() -> new BaseFoodItem(64,2,0.6F));
    public static final RegistryObject<Item> SALMON_ROE = ITEMS.register("salmon_roe",() -> new BaseFoodItem(64,2,0.6F));

    //食材系アイテム（飲料・ジャム系）
    public static final RegistryObject<Item> SWEET_BERRY_JAM = ITEMS.register("sweet_berry_jam",() -> new BaseDrinkItem(64,3,0.6F));
    public static final RegistryObject<Item> TOMATO_JAM = ITEMS.register("tomato_jam",() -> new BaseDrinkItem(64,3,0.6F));
    public static final RegistryObject<Item> GLOW_BERRY_JAM = ITEMS.register("glow_berry_jam",() -> new BaseDrinkItem(64,3,0.3F));
    public static final RegistryObject<Item> CHORUS_FRUIT_JAM = ITEMS.register("chorus_fruit_jam",() -> new BaseDrinkItem(64,4,0.6F));
    public static final RegistryObject<Item> APPLE_JAM = ITEMS.register("apple_jam",() -> new BaseDrinkItem(64,4,0.6F));
    public static final RegistryObject<Item> LEMON_JAM = ITEMS.register("lemon_jam",() -> new BaseDrinkItem(64,3,0.4F));
    public static final RegistryObject<Item> MELON_JAM = ITEMS.register("melon_jam",() -> new BaseDrinkItem(64,3,0.5F));
    public static final RegistryObject<Item> MILK_BOTTLE = ITEMS.register("milk_bottle",() -> new BaseDrinkItem(64,2,0.3F));
    public static final RegistryObject<Item> APPLE_JUICE = ITEMS.register("apple_juice",() -> new BaseDrinkItem(64,4,0.4F));
    public static final RegistryObject<Item> LEMON_JUICE = ITEMS.register("lemon_juice",() -> new BaseDrinkItem(64,3,0.4F));
    public static final RegistryObject<Item> TOMATO_JUICE = ITEMS.register("tomato_juice",() -> new BaseDrinkItem(64,4,0.4F));
    public static final RegistryObject<Item> CARROT_JUICE = ITEMS.register("carrot_juice",() -> new BaseDrinkItem(64,4,1.0F));
    public static final RegistryObject<Item> WHEAT_JUICE = ITEMS.register("wheat_juice",() -> new BaseDrinkItem(64,3,0.6F));
    public static final RegistryObject<Item> MELON_JUICE = ITEMS.register("melon_juice",() -> new BaseDrinkItem(64,3,0.6F));
    public static final RegistryObject<Item> SWEET_BERRY_JUICE = ITEMS.register("sweet_berry_juice",() -> new BaseDrinkItem(64,3,0.6F));
    public static final RegistryObject<Item> GLOW_BERRY_JUICE = ITEMS.register("glow_berry_juice",() -> new BaseDrinkItem(64,3,0.6F));
    public static final RegistryObject<Item> CHORUS_FRUIT_JUICE = ITEMS.register("chorus_fruit_juice",() -> new BaseDrinkItem(64,3,0.6F));
    public static final RegistryObject<Item> HONEY_LEMON_JUICE = ITEMS.register("honey_lemon_juice",() -> new BaseDrinkItem(64,7,0.6F));
    public static final RegistryObject<Item> PUMPKIN_JUICE = ITEMS.register("pumpkin_juice",() -> new BaseDrinkItem(64,3,0.6F));
    public static final RegistryObject<Item> PUMPKIN_JAM = ITEMS.register("pumpkin_jam",() -> new BaseDrinkItem(64,3,0.6F));

    //食材系アイテム（ソース系）
    public static final RegistryObject<Item> TOMATO_SAUCE = ITEMS.register("tomato_sauce",CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> CHEESE_SAUCE = ITEMS.register("cheese_sauce",CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> VINAIGRETTE_SAUCE = ITEMS.register("vinaigrette_sauce",CommonAlchemyMaterial::new);
    public static final RegistryObject<Item> CREAM_SAUCE = ITEMS.register("cream_sauce",CommonAlchemyMaterial::new);

    //食材系アイテム（スープ系）
    public static final RegistryObject<Item> TOMATO_SOUP = ITEMS.register("tomato_soup",() -> new BaseDrinkItem(16,6,0.6F));
    public static final RegistryObject<Item> CABBAGE_AND_EGG_SOUP = ITEMS.register("cabbage_and_egg_soup",() -> new BaseDrinkItem(16,6,0.6F));
    public static final RegistryObject<Item> ONION_SOUP = ITEMS.register("onion_soup",() -> new BaseDrinkItem(16,6,0.6F));
    public static final RegistryObject<Item> TOMATO_CREAM_SOUP = ITEMS.register("tomato_cream_soup",() -> new BaseDrinkItem(16,7,0.6F));
    public static final RegistryObject<Item> CHICKEN_NOODLE_SOUP = ITEMS.register("chicken_noodle_soup",() -> new BaseDrinkItem(16,12,1.6F));
    public static final RegistryObject<Item> BEEF_STEW = ITEMS.register("beef_stew",() -> new BaseDrinkItem(16,16,1.6F));
    public static final RegistryObject<Item> SEAFOOD_CHOWDER = ITEMS.register("seafood_chowder",() -> new BaseDrinkItem(16,14,1.6F));
    public static final RegistryObject<Item> PUMPKIN_THICK_SOUP = ITEMS.register("pumpkin_thick_soup",() -> new BaseDrinkItem(16,6,1.2F));
    public static final RegistryObject<Item> POTATO_THICK_SOUP = ITEMS.register("potato_thick_soup",() -> new BaseDrinkItem(16,6,1.2F));


    //食材系アイテム（パスタ・ご飯系）
    public static final RegistryObject<Item> MEAT_SAUCE_PASTA = ITEMS.register("meat_sauce_pasta",() -> new BaseFoodItem(8,14,1.2F));
    public static final RegistryObject<Item> CREAM_PASTA = ITEMS.register("cream_pasta",() -> new BaseFoodItem(8,12,1.2F));
    public static final RegistryObject<Item> MUSHROOM_RISOTTO = ITEMS.register("mushroom_risotto",() -> new BaseFoodItem(8,13,1.4F));
    public static final RegistryObject<Item> CHEESE_RISOTTO = ITEMS.register("cheese_risotto",() -> new BaseFoodItem(8,13,1.4F));
    public static final RegistryObject<Item> TOMATO_RISOTTO = ITEMS.register("tomato_risotto",() -> new BaseFoodItem(8,13,1.4F));
    public static final RegistryObject<Item> FRIED_RICE = ITEMS.register("fried_rice",() -> new BaseFoodItem(8,13,1.4F));
    public static final RegistryObject<Item> OMELETTE_RICE = ITEMS.register("omelette_rice",() -> new BaseFoodItem(8,16,1.4F));
    public static final RegistryObject<Item> RICE_BALL = ITEMS.register("rice_ball",() -> new BaseFoodItem(16,6,1.2F));
    public static final RegistryObject<Item> SALMON_SUSHI = ITEMS.register("salmon_sushi",() -> new BaseFoodItem(16,7,1.4F));
    public static final RegistryObject<Item> KOMBUJIME_COD_SUSHI = ITEMS.register("konbujime_cod_sushi",() -> new BaseFoodItem(16,7,1.2F));
    public static final RegistryObject<Item> SUSHI_ROLLS = ITEMS.register("sushi_rolls",() -> new BaseFoodItem(16,8,1.4F));

    //食材系アイテム（パン・焼き菓子系）
    public static final RegistryObject<Item> CHEESE_BREAD = ITEMS.register("cheese_bread",() -> new BaseFoodItem(16,8,1.2F));
    public static final RegistryObject<Item> ONION_BREAD = ITEMS.register("onion_bread",() -> new BaseFoodItem(16,8,1.2F));
    public static final RegistryObject<Item> TOMATO_FOCACCIA = ITEMS.register("tomato_focaccia",() -> new BaseFoodItem(16,8,1.2F));
    public static final RegistryObject<Item> PIZZA_DOUGH = ITEMS.register("pizza_dough",() -> new BaseFoodItem(64,2,0.6F));
    public static final RegistryObject<Item> PIZZA_BEFORE_BAKING = ITEMS.register("pizza_before_baking",() -> new BaseFoodItem(16,5,0.6F));
    public static final RegistryObject<Item> PIZZA = ITEMS.register("pizza",() -> new BaseFoodItem(8,16,1.8F));
    public static final RegistryObject<Item> CALZONE_BEFORE_BAKING = ITEMS.register("calzone_before_baking",() -> new BaseFoodItem(16,5,0.6F));
    public static final RegistryObject<Item> CALZONE = ITEMS.register("calzone",() -> new BaseFoodItem(16,12,1.2F));
    public static final RegistryObject<Item> CHEESE_CRACKER = ITEMS.register("cheese_cracker",() -> new BaseFoodItem(64,6,0.8F));
    public static final RegistryObject<Item> CHEESE_CAKE = ITEMS.register("cheese_cake",() -> new BaseFoodItem(16,4,0.4F));
    public static final RegistryObject<Item> CHOCOLATE_CAKE = ITEMS.register("chocolate_cake",() -> new BaseFoodItem(16,4,0.4F));
    public static final RegistryObject<Item> LEMON_CAKE = ITEMS.register("lemon_cake",() -> new BaseFoodItem(16,4,0.4F));
    public static final RegistryObject<Item> APPLE_PIE = ITEMS.register("apple_pie",() -> new BaseFoodItem(16,4,0.4F));

    //食材系アイテム(野菜系）
    public static final RegistryObject<Item> COLESLAW = ITEMS.register("coleslaw",() -> new BaseFoodItem(16,6,0.4F));
    public static final RegistryObject<Item> CHEESE_BAKED_POTATO = ITEMS.register("cheese_baked_potato",() -> new BaseFoodItem(16,6,1.2F));
    public static final RegistryObject<Item> ONION_RING = ITEMS.register("onion_ring",() -> new BaseFoodItem(16,4,0.4f));
    public static final RegistryObject<Item> GRILLED_TOMATO_AND_CHEESE = ITEMS.register("grilled_tomato_and_cheese",() -> new BaseFoodItem(16,5,0.6f));
    public static final RegistryObject<Item> CABBAGE_ROLL = ITEMS.register("cabbage_roll",() -> new BaseFoodItem(16,8,0.8f));
    public static final RegistryObject<Item> FRIED_POTATO = ITEMS.register("fried_potato",() -> new BaseFoodItem(16,5,1.4f));
    public static final RegistryObject<Item> GREEN_SALAD = ITEMS.register("green_salad",() -> new BaseFoodItem(16,8,0.4f));
    public static final RegistryObject<Item> POTATO_SALAD = ITEMS.register("potato_salad",() -> new BaseFoodItem(16,8,0.6f));

    //食材系アイテム（肉系）
    public static final RegistryObject<Item> FRIED_CHICKEN = ITEMS.register("fried_chicken",() -> new BaseFoodItem(8,9,1.2F));
    public static final RegistryObject<Item> FRIED_FISH = ITEMS.register("fried_fish",() -> new BaseFoodItem(8,8,1.2F));
    public static final RegistryObject<Item> HAMBURG_STEAK = ITEMS.register("hamburg_steak",() -> new BaseFoodItem(16,8,1.6F));
    public static final RegistryObject<Item> HAMBURGER = ITEMS.register("hamburger",() -> new BaseFoodItem(8,14,1.6F));
    public static final RegistryObject<Item> STEVES_LAVA_CHICKEN = ITEMS.register("steves_lava_chicken", Steaves_Lava_Chicken::new);

    //食材系アイテム（デザート・スナック系）
    public static final RegistryObject<Item> ICE_CREAM = ITEMS.register("ice_cream",() -> new BaseFoodItem(16,5,0.4F));
    public static final RegistryObject<Item> CHOCOLATE_ICE_CREAM = ITEMS.register("chocolate_ice_cream",() -> new BaseFoodItem(16,6,0.5F));
    public static final RegistryObject<Item> LEMON_ICE_CREAM = ITEMS.register("lemon_ice_cream",() -> new BaseFoodItem(16,5,0.3F));
    public static final RegistryObject<Item> APPLE_ICE_CREAM = ITEMS.register("apple_ice_cream",() -> new BaseFoodItem(16,6,0.4F));
    public static final RegistryObject<Item> SWEET_BERRY_SMOOTHIE = ITEMS.register("sweet_berry_smoothie",() -> new BaseDrinkItem(64,4,0.5F));
    public static final RegistryObject<Item> GLOW_BERRY_SMOOTHIE = ITEMS.register("glow_berry_smoothie",() -> new BaseDrinkItem(64,4,0.6F));
    public static final RegistryObject<Item> RICE_PUDDING = ITEMS.register("rice_pudding",() -> new BaseFoodItem(16,6,1.2F));
    public static final RegistryObject<Item> JAM_BUN = ITEMS.register("jam_bun",() -> new BaseFoodItem(16,9,1.2F));

    //完全食
    public static final RegistryObject<Item> OMG_STEW = ITEMS.register("omg_stew", OMG_Stew::new);





    //アイテムリストの登録用
    public static void register(IEventBus eventBus){
        ITEMS.register(eventBus);
    }
}
