package jp.nogami_rion.alchemical_power.init;


import jp.nogami_rion.alchemical_power.Alchemical_power;
import jp.nogami_rion.alchemical_power.item.*;
import jp.nogami_rion.alchemical_power.item.custom.FuelItem;
import net.minecraft.world.item.*;
import net.minecraftforge.eventbus.api.IEventBus;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class itemlist {
    //アイテムリストを生成
    private static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, Alchemical_power.MODID);
    public static final RegistryObject<Item> T0_PANAKEIA = ITEMS.register("t0_panakeia", T0_Panakeia::new);
    public static final RegistryObject<Item> T1_PANAKEIA = ITEMS.register("t1_panakeia", T1_Panakeia::new);
    public static final RegistryObject<Item> T2_PANAKEIA = ITEMS.register("t2_panakeia", T2_Panakeia::new);
    public static final RegistryObject<Item> T3_PANAKEIA = ITEMS.register("t3_panakeia", T3_Panakeia::new);
    public static final RegistryObject<Item> T4_PANAKEIA = ITEMS.register("t4_panakeia", T4_Panakeia::new);
    public static final RegistryObject<Item> T5_PANAKEIA = ITEMS.register("t5_panakeia", T5_Panakeia::new);
    public static final RegistryObject<Item> T6_PANAKEIA = ITEMS.register("t6_panakeia", T6_Panakeia::new);
    public static final RegistryObject<Item> T7_PANAKEIA = ITEMS.register("t7_panakeia", T7_Panakeia::new);
    public static final RegistryObject<Item> PANAKEIA_BEARING_STONE = ITEMS.register("panakeia_bearing_stone",() -> new BlockItem(blocklist.PANAKEIA_BEARING_STONE.get(), new Item.Properties()));
    public static final RegistryObject<Item> ALCHEMY_BEGINNERS_KIT = ITEMS.register("alchemy_beginners_kit",Alchemy_Bginners_Kit::new);
    public static final RegistryObject<Item> ALCHEMICAL_PROCESSING_COPPER = ITEMS.register("alchemical_processing_copper", Alchemical_Processing_Copper::new);
    public static final RegistryObject<Item> ALCHEMICAL_PROCESSING_IRON = ITEMS.register("alchemical_processing_iron", Alchemical_Processing_Iron::new);
    public static final RegistryObject<Item> ALCHEMICAL_PROCESSING_GOLD = ITEMS.register("alchemical_processing_gold", Alchemical_Processing_Gold::new);
    public static final RegistryObject<Item> ALCHEMICAL_PROCESSING_DIAMOND = ITEMS.register("alchemical_processing_diamond", Alchemical_Processing_Diamond::new);
    public static final RegistryObject<Item> ALCHEMICAL_PROCESSING_EMERALD = ITEMS.register("alchemical_processing_emerald", Alchemical_Processing_Emerald::new);
    public static final RegistryObject<Item> ALCHEMICAL_PROCESSING_NETHERITE = ITEMS.register("alchemical_processing_netherite", Alchemical_Processing_Netherite::new);
    public static final RegistryObject<Item> UNITE_ALLOY = ITEMS.register("unite_alloy", Unite_Alloy::new);
    public static final RegistryObject<Item> ALCHEMICAL_PROCESSING_COPPER_BLOCK = ITEMS.register("alchemical_processing_copper_block",() -> new BlockItem(blocklist.ALCHEMICAL_PROCESSING_COPPER_BLOCK.get(), new Item.Properties()));
    public static final RegistryObject<Item> ALCHEMICAL_PROCESSING_IRON_BLOCK = ITEMS.register("alchemical_processing_iron_block",() -> new BlockItem(blocklist.ALCHEMICAL_PROCESSING_IRON_BLOCK.get(), new Item.Properties()));
    public static final RegistryObject<Item> ALCHEMICAL_PROCESSING_GOLD_BLOCK = ITEMS.register("alchemical_processing_gold_block",() -> new BlockItem(blocklist.ALCHEMICAL_PROCESSING_GOLD_BLOCK.get(), new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> ALCHEMICAL_PROCESSING_DIAMOND_BLOCK = ITEMS.register("alchemical_processing_diamond_block",() -> new BlockItem(blocklist.ALCHEMICAL_PROCESSING_DIAMOND_BLOCK.get(), new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> ALCHEMICAL_PROCESSING_EMERALD_BLOCK = ITEMS.register("alchemical_processing_emerald_block",() -> new BlockItem(blocklist.ALCHEMICAL_PROCESSING_EMERALD_BLOCK.get(), new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> ALCHEMICAL_PROCESSING_NETHERITE_BLOCK = ITEMS.register("alchemical_processing_netherite_block",() -> new BlockItem(blocklist.ALCHEMICAL_PROCESSING_NETHERITE_BLOCK.get(), new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> UNITE_ALLOY_BLOCK = ITEMS.register("unite_alloy_block",() -> new BlockItem(blocklist.UNITE_ALLOY_BLOCK.get(), new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> ALCHEMY_TABLE = ITEMS.register("alchemy_table",() -> new BlockItem(blocklist.ALCHEMY_TABLE.get(), new Item.Properties()));
    public static final RegistryObject<Item> PANAKEIA_REED_T0 = ITEMS.register("panakeia_reed_t0",() -> new BlockItem(blocklist.PANAKEIA_REED_T0.get(), new Item.Properties()));
    public static final RegistryObject<Item> PANAKEIA_REED_T1 = ITEMS.register("panakeia_reed_t1",() -> new BlockItem(blocklist.PANAKEIA_REED_T1.get(), new Item.Properties()));
    public static final RegistryObject<Item> PANAKEIA_REED_T2 = ITEMS.register("panakeia_reed_t2",() -> new BlockItem(blocklist.PANAKEIA_REED_T2.get(), new Item.Properties()));
    public static final RegistryObject<Item> PANAKEIA_REED_T3 = ITEMS.register("panakeia_reed_t3",() -> new BlockItem(blocklist.PANAKEIA_REED_T3.get(), new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> PANAKEIA_REED_T4 = ITEMS.register("panakeia_reed_t4",() -> new BlockItem(blocklist.PANAKEIA_REED_T4.get(), new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> PANAKEIA_REED_T5 = ITEMS.register("panakeia_reed_t5",() -> new BlockItem(blocklist.PANAKEIA_REED_T5.get(), new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> PANAKEIA_REED_T6 = ITEMS.register("panakeia_reed_t6",() -> new BlockItem(blocklist.PANAKEIA_REED_T6.get(), new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> PANAKEIA_REED_T7 = ITEMS.register("panakeia_reed_t7",() -> new BlockItem(blocklist.PANAKEIA_REED_T7.get(), new Item.Properties().rarity(Rarity.EPIC)));
    public static final RegistryObject<Item> ALCHEMY_INTERMEDIATE_KIT = ITEMS.register("alchemy_intermediate_kit", Alchemy_Intermediate_Kit::new);
    public static final RegistryObject<Item> ALCHEMY_EXPERTS_KIT = ITEMS.register("alchemy_experts_kit", Alchemy_Experts_Kit::new);
    public static final RegistryObject<Item> ULTIMATE_ALCHEMY_KIT = ITEMS.register("ultimate_alchemy_kit", Ultimate_Alchemy_Kit::new);
    public static final RegistryObject<Item> HERMES_WORKBENCH = ITEMS.register("hermes_workbench",() -> new BlockItem(blocklist.HERMES_WORKBENCH.get(), new Item.Properties()));
    public static final RegistryObject<Item> TRANSCENDENTAL_TABLE = ITEMS.register("transcendental_table",() -> new BlockItem(blocklist.TRANSCENDENTAL_TABLE.get(), new Item.Properties()));
    public static final RegistryObject<Item> HIGH_DENSITY_ALCHEMICAL_COPPER = ITEMS.register("high_density_alchemical_copper", High_Density_Alchemical_Copper::new);
    public static final RegistryObject<Item> HIGH_DENSITY_ALCHEMICAL_IRON = ITEMS.register("high_density_alchemical_iron", High_Density_Alchemical_Iron::new);
    public static final RegistryObject<Item> HIGH_DENSITY_ALCHEMICAL_GOLD = ITEMS.register("high_density_alchemical_gold", High_Density_Alchemical_Gold::new);
    public static final RegistryObject<Item> HIGH_DENSITY_ALCHEMICAL_DIAMOND = ITEMS.register("high_density_alchemical_diamond", High_Density_Alchemical_Diamond::new);
    public static final RegistryObject<Item> HIGH_DENSITY_ALCHEMICAL_EMERALD = ITEMS.register("high_density_alchemical_emerald", High_Density_Alchemical_Emerald::new);
    public static final RegistryObject<Item> HIGH_DENSITY_ALCHEMICAL_NETHERITE = ITEMS.register("high_density_alchemical_netherite", High_Density_Alchemical_Netherite::new);
    public static final RegistryObject<Item> HIGH_DENSITY_UNITE_ALLOY = ITEMS.register("high_density_unite_alloy", High_Density_Unite_Alloy::new);
    public static final RegistryObject<Item> WISDOM_CRYSTAL = ITEMS.register("wisdom_crystal", Wisdom_Crystal::new);
    public static final RegistryObject<Item> COURAGE_CRYSTAL = ITEMS.register("courage_crystal", Courage_Crystal::new);
    public static final RegistryObject<Item> JUSTICE_CRYSTAL = ITEMS.register("justice_crystal", Justice_Crystal::new);
    public static final RegistryObject<Item> LOVE_CRYSTAL = ITEMS.register("love_crystal", Love_Crystal::new);
    public static final RegistryObject<Item> HOPE_CRYSTAL = ITEMS.register("hope_crystal", Hope_Crystal::new);
    public static final RegistryObject<Item> TEMPERANCE_CRYSTAL = ITEMS.register("temperance_crystal", Temperance_Crystal::new);
    public static final RegistryObject<Item> FAITH_CRYSTAL = ITEMS.register("faith_crystal", Faith_Crystal::new);
    public static final RegistryObject<Item> ORIGIN_OF_WISDOM = ITEMS.register("origin_of_wisdom", Origin_of_Wisdom::new);
    public static final RegistryObject<Item> ORIGIN_OF_COURAGE = ITEMS.register("origin_of_courage", Origin_of_Courage::new);
    public static final RegistryObject<Item> ORIGIN_OF_JUSTICE = ITEMS.register("origin_of_justice", Origin_of_Justice::new);
    public static final RegistryObject<Item> ORIGIN_OF_LOVE = ITEMS.register("origin_of_love", Origin_of_Love::new);
    public static final RegistryObject<Item> ORIGIN_OF_HOPE = ITEMS.register("origin_of_hope", Origin_of_Hope::new);
    public static final RegistryObject<Item> ORIGIN_OF_TEMPERANCE = ITEMS.register("origin_of_temperance", Origin_of_Temperance::new);
    public static final RegistryObject<Item> ORIGIN_OF_FAITH = ITEMS.register("origin_of_faith", Origin_of_Faith::new);
    public static final RegistryObject<Item> BLANK_RUNE = ITEMS.register("blank_rune", Blank_Rune::new);
    public static final RegistryObject<Item> VOID_RUNE = ITEMS.register("void_rune", Void_Rune::new);
    public static final RegistryObject<Item> BASIC_ENGRAVING_INK = ITEMS.register("basic_engraving_ink", Basic_Engraving_Ink::new);
    public static final RegistryObject<Item> ADVANCED_ENGRAVING_INK = ITEMS.register("advanced_engraving_ink", Advanced_Engraving_Ink::new);
    public static final RegistryObject<Item> ELITE_ENGRAVING_INK = ITEMS.register("elite_engraving_ink", Elite_Engraving_Ink::new);
    public static final RegistryObject<Item> ULTIMATE_ENGRAVING_INK = ITEMS.register("ultimate_engraving_ink", Ultimate_Engraving_Ink::new);
    public static final RegistryObject<Item> BASIC_GRINDING_RUNE = ITEMS.register("basic_grinding_rune", Basic_Grinding_Rune::new);
    public static final RegistryObject<Item> ADVANCED_GRINDING_RUNE = ITEMS.register("advanced_grinding_rune", Advanced_Grinding_Rune::new);
    public static final RegistryObject<Item> ELITE_GRINDING_RUNE = ITEMS.register("elite_grinding_rune", Elite_Grinding_Rune::new);
    public static final RegistryObject<Item> ULTIMATE_GRINDING_RUNE = ITEMS.register("ultimate_grinding_rune", Ultimate_Grinding_Rune::new);
    public static final RegistryObject<Item> BASIC_GRANULATING_RUNE = ITEMS.register("basic_granulating_rune", Basic_Granulating_Rune::new);
    public static final RegistryObject<Item> ADVANCED_GRANULATING_RUNE = ITEMS.register("advanced_granulating_rune", Advanced_Granulating_Rune::new);
    public static final RegistryObject<Item> ELITE_GRANULATING_RUNE = ITEMS.register("elite_granulating_rune", Elite_Granulating_Rune::new);
    public static final RegistryObject<Item> ULTIMATE_GRANULATING_RUNE = ITEMS.register("ultimate_granulating_rune", Ultimate_Granulating_Rune::new);
    public static final RegistryObject<Item> BASIC_SOFTENING_RUNE = ITEMS.register("basic_softening_rune", Basic_Softening_Rune::new);
    public static final RegistryObject<Item> ADVANCED_SOFTENING_RUNE = ITEMS.register("advanced_softening_rune", Advanced_Softening_Rune::new);
    public static final RegistryObject<Item> ELITE_SOFTENING_RUNE = ITEMS.register("elite_softening_rune", Elite_Softening_Rune::new);
    public static final RegistryObject<Item> ULTIMATE_SOFTENING_RUNE = ITEMS.register("ultimate_softening_rune", Ultimate_Softening_Rune::new);
    public static final RegistryObject<Item> BASIC_PURIFICATION_RUNE = ITEMS.register("basic_purification_rune", Basic_Purification_Rune::new);
    public static final RegistryObject<Item> ADVANCED_PURIFICATION_RUNE = ITEMS.register("advanced_purification_rune", Advanced_Purification_Rune::new);
    public static final RegistryObject<Item> ELITE_PURIFICATION_RUNE = ITEMS.register("elite_purification_rune", Basic_Purification_Rune::new);
    public static final RegistryObject<Item> ULTIMATE_PURIFICATION_RUNE = ITEMS.register("ultimate_purification_rune", Ultimate_Purification_Rune::new);
    public static final RegistryObject<Item> CRUSHED_RAW_COPPER = ITEMS.register("crushed_raw_copper", Crushed_Raw_Copper::new);
    public static final RegistryObject<Item> CRUSHED_RAW_IRON = ITEMS.register("crushed_raw_iron", Crushed_Raw_Iron::new);
    public static final RegistryObject<Item> CRUSHED_RAW_GOLD = ITEMS.register("crushed_raw_gold", Crushed_Raw_Gold::new);
    public static final RegistryObject<Item> CRUSHED_DIAMOND_ORE = ITEMS.register("crushed_diamond_ore", Crushed_Diamond_Ore::new);
    public static final RegistryObject<Item> CRUSHED_EMERALD_ORE = ITEMS.register("crushed_emerald_ore", Crushed_Emerald_Ore::new);
    public static final RegistryObject<Item> CRUSHED_ANCIENT_DEBRIS = ITEMS.register("crushed_ancient_debris", Crushed_Ancient_Debris::new);
    public static final RegistryObject<Item> GRANULATED_COPPER = ITEMS.register("granulated_copper", Granulated_Copper::new);
    public static final RegistryObject<Item> GRANULATED_IRON = ITEMS.register("granulated_iron", Granulated_Iron::new);
    public static final RegistryObject<Item> GRANULATED_GOLD = ITEMS.register("granulated_gold", Granulated_Gold::new);
    public static final RegistryObject<Item> GRANULATED_DIAMOND = ITEMS.register("granulated_diamond", Granulated_Diamond::new);
    public static final RegistryObject<Item> GRANULATED_EMERALD = ITEMS.register("granulated_emerald", Granulated_Emerald::new);
    public static final RegistryObject<Item> GRANULATED_ANCIENT_DEBRIS = ITEMS.register("granulated_ancient_debris", Granulated_Ancient_Debris::new);
    public static final RegistryObject<Item> SOFTENED_COPPER = ITEMS.register("softened_copper", Softened_Copper::new);
    public static final RegistryObject<Item> SOFTENED_IRON = ITEMS.register("softened_iron", Softened_Iron::new);
    public static final RegistryObject<Item> SOFTENED_GOLD = ITEMS.register("softened_gold", Softened_Gold::new);
    public static final RegistryObject<Item> SOFTENED_DIAMOND = ITEMS.register("softened_diamond", Softened_Diamond::new);
    public static final RegistryObject<Item> SOFTENED_EMERALD = ITEMS.register("softened_emerald", Softened_Emerald::new);
    public static final RegistryObject<Item> SOFTENED_ANCIENT_DEBRIS = ITEMS.register("softened_ancient_debris", Softened_Ancient_Debris::new);
    public static final RegistryObject<Item> PURIFIED_COPPER = ITEMS.register("purified_copper", Purified_Copper::new);
    public static final RegistryObject<Item> PURIFIED_IRON = ITEMS.register("purified_iron", Purified_Iron::new);
    public static final RegistryObject<Item> PURIFIED_GOLD = ITEMS.register("purified_gold", Purified_Gold::new);
    public static final RegistryObject<Item> PURIFIED_DIAMOND = ITEMS.register("purified_diamond", Purified_Diamond::new);
    public static final RegistryObject<Item> PURIFIED_EMERALD = ITEMS.register("purified_emerald", Purified_Emerald::new);
    public static final RegistryObject<Item> PURIFIED_ANCIENT_DEBRIS = ITEMS.register("purified_ancient_debris", Purified_Ancient_Debris::new);
    public static final RegistryObject<Item> ALCHEMICAL_ENGRAVER = ITEMS.register("alchemical_engraver",() -> new BlockItem(blocklist.ALCHEMICAL_ENGRAVER.get(), new Item.Properties()));
    public static final RegistryObject<Item> RUNE_ACTIVATOR = ITEMS.register("rune_activator",() -> new BlockItem(blocklist.RUNE_ACTIVATOR.get(), new Item.Properties()));
    public static final RegistryObject<Item> X9_COBBLESTONE = ITEMS.register("x9_cobblestone",() -> new BlockItem(blocklist.X9_COBBLESTONE.get(), new Item.Properties()));
    public static final RegistryObject<Item> X225_COBBLESTONE = ITEMS.register("x225_cobblestone",() -> new BlockItem(blocklist.X225_COBBLESTONE.get(), new Item.Properties()));
    public static final RegistryObject<Item> X38025_COBBLESTONE = ITEMS.register("x38025_cobblestone",() -> new BlockItem(blocklist.X38025_COBBLESTONE.get(), new Item.Properties()));
    public static final RegistryObject<Item> IMITATED_BEDROCK = ITEMS.register("imitated_bedrock",() -> new BlockItem(blocklist.IMITATED_BEDROCK.get(), new Item.Properties()));
    public static final RegistryObject<Item> PHILOSOPHERS_STONE = ITEMS.register("philosophers_stone", Philosophers_stone::new);
    public static final RegistryObject<Item> ARCANE_STAR = ITEMS.register("arcane_star", Arcane_Star::new);
    public static final RegistryObject<Item> ARCANE_DRAGON_EGG = ITEMS.register("arcane_dragon_egg", Arcane_Dragon_Egg::new);
    public static final RegistryObject<Item> SINGULARITY = ITEMS.register("singularity", Singularity::new);
    public static final RegistryObject<Item> T1_COMBUSTION_RUNE = ITEMS.register("t1_combustion_rune",() -> new FuelItem(new Item.Properties().rarity(Rarity.COMMON),2400));
    public static final RegistryObject<Item> T2_COMBUSTION_RUNE = ITEMS.register("t2_combustion_rune",() -> new FuelItem(new Item.Properties().rarity(Rarity.COMMON),3600));
    public static final RegistryObject<Item> T3_COMBUSTION_RUNE = ITEMS.register("t3_combustion_rune",() -> new FuelItem(new Item.Properties().rarity(Rarity.UNCOMMON),5400));
    public static final RegistryObject<Item> T4_COMBUSTION_RUNE = ITEMS.register("t4_combustion_rune",() -> new FuelItem(new Item.Properties().rarity(Rarity.UNCOMMON),8100));
    public static final RegistryObject<Item> T5_COMBUSTION_RUNE = ITEMS.register("t5_combustion_rune",() -> new FuelItem(new Item.Properties().rarity(Rarity.RARE),12150));
    public static final RegistryObject<Item> T6_COMBUSTION_RUNE = ITEMS.register("t6_combustion_rune",() -> new FuelItem(new Item.Properties().rarity(Rarity.RARE),18225));
    public static final RegistryObject<Item> ETERNAL_FUEL = ITEMS.register("eternal_fuel",() -> new FuelItem(new Item.Properties().rarity(Rarity.EPIC),Integer.MAX_VALUE));
    public static final RegistryObject<Item> T1_COMBUSTION_RUNE_BLOCK = ITEMS.register("t1_combustion_rune_block",() -> new BlockItem(blocklist.T1_COMBUSTION_RUNE_BLOCK.get(), new Item.Properties()));
    public static final RegistryObject<Item> T2_COMBUSTION_RUNE_BLOCK = ITEMS.register("t2_combustion_rune_block",() -> new BlockItem(blocklist.T2_COMBUSTION_RUNE_BLOCK.get(), new Item.Properties()));
    public static final RegistryObject<Item> T3_COMBUSTION_RUNE_BLOCK = ITEMS.register("t3_combustion_rune_block",() -> new BlockItem(blocklist.T3_COMBUSTION_RUNE_BLOCK.get(), new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> T4_COMBUSTION_RUNE_BLOCK = ITEMS.register("t4_combustion_rune_block",() -> new BlockItem(blocklist.T4_COMBUSTION_RUNE_BLOCK.get(), new Item.Properties().rarity(Rarity.UNCOMMON)));
    public static final RegistryObject<Item> T5_COMBUSTION_RUNE_BLOCK = ITEMS.register("t5_combustion_rune_block",() -> new BlockItem(blocklist.T5_COMBUSTION_RUNE_BLOCK.get(), new Item.Properties().rarity(Rarity.RARE)));
    public static final RegistryObject<Item> T6_COMBUSTION_RUNE_BLOCK = ITEMS.register("t6_combustion_rune_block",() -> new BlockItem(blocklist.T6_COMBUSTION_RUNE_BLOCK.get(), new Item.Properties().rarity(Rarity.RARE)));

    //アイテムリストの登録用
    public static void register(IEventBus eventBus){
        ITEMS.register(eventBus);
    }
}
